/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.abc.view.main;

import com.abc.controller.AdminControler;
import com.abc.controller.CustomerControler;
import com.abc.controller.UserControler;
import com.abc.model.Customer;
import com.abc.model.Hall;
import com.abc.model.Login;

import com.abc.view.componont.DatePicker;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ComboBoxModel;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.ImageIcon;
import textfield.SearchOptinEvent;
import textfield.SearchOption;

/**
 *
 * @author User
 */
public class AdminMainUser extends javax.swing.JFrame {

    /**
     * Creates new form CustomerUserIView
     */
    public AdminMainUser() {
        initComponents();
        showDate();
        DataTable();
        DataTableHall();
        jDataTableFD.setAutoCreateRowSorter(true);
        //loadComboBoxSD();
        //loadComboBoxLX();
        //loadComboBoxBQ();
        
        

    }
/*
    private void loadComboBoxSD() {

        AdminControler Cc = new AdminControler();
        List<Hall> list = Cc.selectComponentValueHallCap("Standard Hall");

        for (int i = 0; i < list.size(); i++) {

            cmbSDHallID.addItem(list.get(i).getHallId());

        }

    }
    
    private void loadComboBoxBQ() {

        AdminControler Cc = new AdminControler();
        List<Hall> list = Cc.selectComponentValueHallCap("Benquet Hall");

        for (int i = 0; i < list.size(); i++) {

            cmbBQHallID.addItem(list.get(i).getHallId());

        }

    }
    private void loadComboBoxLX() {

        AdminControler Cc = new AdminControler();
        List<Hall> list = Cc.selectComponentValueHallCap("Luxury Hall");

        for (int i = 0; i < list.size(); i++) {

            cmbLXHallID.addItem(list.get(i).getHallId());

        }

    }*/

    public String showDateTime() {

        SimpleDateFormat sdf = new SimpleDateFormat("dd|MM|yyyy  HH:mm:ss");
        Date d = new Date();
        String date = sdf.format(d);

        return date;
    }
    
     public void DataTableHall() {

        AdminControler Cc = new AdminControler();
        List<Hall> list = Cc.listHalls();
        DefaultTableModel DFT = (DefaultTableModel) halltable.getModel();
        DFT.setRowCount(0);
        for (Hall k : list) {

            String id = k.getHallId();
            String hallCap = k.getHallCap();
            String pricePerDay = k.getPricePerDay(); 
            String actype = k.getAcType();
            DFT.addRow(new Object[]{ id,hallCap,pricePerDay,actype });

        }
    }

    public void showDate() {

        SimpleDateFormat sdf = new SimpleDateFormat("dd|MM|yyyy");
        Date d = new Date();
        txtCheckInDateFD.setText(sdf.format(d));
        txtCheckOutDateFD.setText(sdf.format(d));

    }

    public boolean validateSubmit() {

        boolean b = false;
        if (txtNicFD.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Customer NIC is requried");
            txtNicFD.requestFocus();
        } else if (txtNameFD.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Customer Name is requried");
            txtNameFD.requestFocus();

        } else if (txtTeleFD.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Customer Telephone Number is requried");
            txtTeleFD.requestFocus();

        } else if (txtEmailFD.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Customer Email is requried");
            txtEmailFD.requestFocus();

        } else {
            b = true;

        }

        return b;

    }

    public boolean validateSearch() {

        boolean b = false;
        if (txtSearch.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Enter Customer NIC is requried");
            txtSearch.requestFocus();
        } else {

            b = true;

        }

        return b;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        gradientBG2 = new com.abc.view.componont.GradientBG();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        txtNicFD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNameFD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTeleFD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmailFD = new javax.swing.JTextField();
        BookPanel = new javax.swing.JLayeredPane();
        LuxuryHallType = new javax.swing.JLayeredPane();
        Halltype = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnSelectLuxuryHall = new com.abc.view.swing_componont.ButtonOutLine();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtHallId = new javax.swing.JTextField();
        txtCap = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtAc = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        CheckAvailabelPanel = new javax.swing.JLayeredPane();
        checkInCalender = new javax.swing.JLayeredPane();
        txtCheckInDateFD = new javax.swing.JLabel();
        btnCheckInFD = new com.abc.view.swing_componont.ButtonOutLine();
        checkindate = new javax.swing.JLabel();
        checkOutCalender = new javax.swing.JLayeredPane();
        txtCheckOutDateFD = new javax.swing.JLabel();
        btnCheckOutFD = new com.abc.view.swing_componont.ButtonOutLine();
        checkOutdate = new javax.swing.JLabel();
        btnCheckAvailability = new com.abc.view.swing_componont.KButton();
        btnAddBook = new com.abc.view.swing_componont.KButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnCancelBook = new com.abc.view.swing_componont.KButton();
        btnUpdateBook = new com.abc.view.swing_componont.KButton();
        btnDeleteBook = new com.abc.view.swing_componont.KButton();
        cmbNoOfDay = new javax.swing.JComboBox<>();
        cmbBookType = new javax.swing.JComboBox<>();
        cbMonday = new javax.swing.JCheckBox();
        cbSunday = new javax.swing.JCheckBox();
        cbThursday = new javax.swing.JCheckBox();
        cbWednesday = new javax.swing.JCheckBox();
        cbTuesday = new javax.swing.JCheckBox();
        cbFriday = new javax.swing.JCheckBox();
        cbSterday = new javax.swing.JCheckBox();
        btnDeleteCustomer = new com.abc.view.swing_componont.ButtonOutLine();
        btnAddCustomer = new com.abc.view.swing_componont.ButtonOutLine();
        btnUpdateCustomer = new com.abc.view.swing_componont.ButtonOutLine();
        txtSearch = new com.abc.view.swing_componont.MyTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDataTableFD = new javax.swing.JTable();
        btnSearch = new com.abc.view.swing_componont.KButton();
        btnUserSetings = new com.abc.view.swing_componont.KButton();
        btnHallSetings = new com.abc.view.swing_componont.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        halltable = new javax.swing.JTable();
        txt = new textfield.TextFieldSearchOption();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane2.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 73, 227));
        jLabel1.setText("NIC");

        txtNicFD.setBackground(new java.awt.Color(255, 255, 255));
        txtNicFD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNicFD.setForeground(new java.awt.Color(0, 73, 227));
        txtNicFD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 73, 227)));
        txtNicFD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNicFD.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNicFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicFDActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 73, 227));
        jLabel2.setText("Enter Your Information");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 73, 227));
        jLabel3.setText("Name");

        txtNameFD.setBackground(new java.awt.Color(255, 255, 255));
        txtNameFD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameFD.setForeground(new java.awt.Color(0, 73, 227));
        txtNameFD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 73, 227)));
        txtNameFD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNameFD.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNameFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameFDActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 73, 227));
        jLabel4.setText("Telephone Number");

        txtTeleFD.setBackground(new java.awt.Color(255, 255, 255));
        txtTeleFD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTeleFD.setForeground(new java.awt.Color(0, 73, 227));
        txtTeleFD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 73, 227)));
        txtTeleFD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTeleFD.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTeleFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleFDActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 73, 227));
        jLabel5.setText("E-Mail");

        txtEmailFD.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailFD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmailFD.setForeground(new java.awt.Color(0, 73, 227));
        txtEmailFD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 73, 227)));
        txtEmailFD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtEmailFD.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEmailFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailFDActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtNicFD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtNameFD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtTeleFD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtEmailFD, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailFD, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeleFD, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameFD, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNicFD, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36))))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNicFD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNameFD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTeleFD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailFD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        LuxuryHallType.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        Halltype.setBackground(new java.awt.Color(255, 255, 255));
        Halltype.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Halltype.setForeground(new java.awt.Color(255, 255, 255));
        Halltype.setText("Luxury Halls");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Maximum Capacity");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText(" (Per Person)");

        btnSelectLuxuryHall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/building (4).png"))); // NOI18N
        btnSelectLuxuryHall.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnSelectLuxuryHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectLuxuryHallActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel22.setText("Terms and Conditions apply.");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Price Per Day ");

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Hall ID");

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Air Condithion");

        LuxuryHallType.setLayer(Halltype, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(btnSelectLuxuryHall, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(txtHallId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(txtCap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(txtPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(txtAc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LuxuryHallTypeLayout = new javax.swing.GroupLayout(LuxuryHallType);
        LuxuryHallType.setLayout(LuxuryHallTypeLayout);
        LuxuryHallTypeLayout.setHorizontalGroup(
            LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                        .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Halltype, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                                    .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCap, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LuxuryHallTypeLayout.createSequentialGroup()
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtHallId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addComponent(btnSelectLuxuryHall, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        LuxuryHallTypeLayout.setVerticalGroup(
            LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSelectLuxuryHall, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                        .addComponent(Halltype, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                                .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LuxuryHallTypeLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHallId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))))
                .addGap(10, 10, 10)
                .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(313, 313, 313)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        checkInCalender.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        txtCheckInDateFD.setBackground(new java.awt.Color(255, 255, 255));
        txtCheckInDateFD.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        txtCheckInDateFD.setForeground(new java.awt.Color(255, 255, 255));
        txtCheckInDateFD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtCheckInDateFD.setText("10|02|2023");

        btnCheckInFD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/cursor (3).png"))); // NOI18N
        btnCheckInFD.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnCheckInFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInFDActionPerformed(evt);
            }
        });

        checkInCalender.setLayer(txtCheckInDateFD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        checkInCalender.setLayer(btnCheckInFD, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout checkInCalenderLayout = new javax.swing.GroupLayout(checkInCalender);
        checkInCalender.setLayout(checkInCalenderLayout);
        checkInCalenderLayout.setHorizontalGroup(
            checkInCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkInCalenderLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(txtCheckInDateFD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCheckInFD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        checkInCalenderLayout.setVerticalGroup(
            checkInCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkInCalenderLayout.createSequentialGroup()
                .addGroup(checkInCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCheckInDateFD)
                    .addComponent(btnCheckInFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        checkindate.setBackground(new java.awt.Color(204, 204, 204));
        checkindate.setText("Check In Date");

        checkOutCalender.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        txtCheckOutDateFD.setBackground(new java.awt.Color(255, 255, 255));
        txtCheckOutDateFD.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        txtCheckOutDateFD.setForeground(new java.awt.Color(255, 255, 255));
        txtCheckOutDateFD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtCheckOutDateFD.setText("10|02|2023");

        btnCheckOutFD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/cursor (3).png"))); // NOI18N
        btnCheckOutFD.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnCheckOutFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutFDActionPerformed(evt);
            }
        });

        checkOutCalender.setLayer(txtCheckOutDateFD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        checkOutCalender.setLayer(btnCheckOutFD, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout checkOutCalenderLayout = new javax.swing.GroupLayout(checkOutCalender);
        checkOutCalender.setLayout(checkOutCalenderLayout);
        checkOutCalenderLayout.setHorizontalGroup(
            checkOutCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkOutCalenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCheckOutDateFD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheckOutFD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        checkOutCalenderLayout.setVerticalGroup(
            checkOutCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutCalenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCheckOutDateFD)
                .addGap(27, 27, 27))
            .addGroup(checkOutCalenderLayout.createSequentialGroup()
                .addComponent(btnCheckOutFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        checkOutdate.setBackground(new java.awt.Color(204, 204, 204));
        checkOutdate.setText("Check Out Date");

        CheckAvailabelPanel.setLayer(checkInCalender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CheckAvailabelPanel.setLayer(checkindate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CheckAvailabelPanel.setLayer(checkOutCalender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CheckAvailabelPanel.setLayer(checkOutdate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout CheckAvailabelPanelLayout = new javax.swing.GroupLayout(CheckAvailabelPanel);
        CheckAvailabelPanel.setLayout(CheckAvailabelPanelLayout);
        CheckAvailabelPanelLayout.setHorizontalGroup(
            CheckAvailabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckAvailabelPanelLayout.createSequentialGroup()
                .addGroup(CheckAvailabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CheckAvailabelPanelLayout.createSequentialGroup()
                        .addComponent(checkInCalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkOutCalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CheckAvailabelPanelLayout.createSequentialGroup()
                        .addComponent(checkindate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkOutdate)))
                .addContainerGap())
        );
        CheckAvailabelPanelLayout.setVerticalGroup(
            CheckAvailabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckAvailabelPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(CheckAvailabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOutdate)
                    .addComponent(checkindate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CheckAvailabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkInCalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkOutCalender, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnCheckAvailability.setText("Check Availability");
        btnCheckAvailability.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnCheckAvailability.setkBorderRadius(65);
        btnCheckAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAvailabilityActionPerformed(evt);
            }
        });

        btnAddBook.setText("ADD Book");
        btnAddBook.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnAddBook.setkBorderRadius(65);
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Select Your Prefered Match");

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("What Day You Looking for");

        btnCancelBook.setText("Cancel Book");
        btnCancelBook.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnCancelBook.setkBorderRadius(65);
        btnCancelBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelBookActionPerformed(evt);
            }
        });

        btnUpdateBook.setText("Update BOOK");
        btnUpdateBook.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnUpdateBook.setkBorderRadius(65);
        btnUpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBookActionPerformed(evt);
            }
        });

        btnDeleteBook.setText("Delete Book");
        btnDeleteBook.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnDeleteBook.setkBorderRadius(65);
        btnDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookActionPerformed(evt);
            }
        });

        cmbNoOfDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cmbNoOfDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNoOfDayActionPerformed(evt);
            }
        });

        cmbBookType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A Given Date", "A Continues Period", "A Specific Day" }));
        cmbBookType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBookTypeActionPerformed(evt);
            }
        });

        cbMonday.setText("Monday");

        cbSunday.setText("Sunday");

        cbThursday.setText("Thursday");

        cbWednesday.setText("Wednesday");

        cbTuesday.setText("Tuesday");

        cbFriday.setText("Friday");
        cbFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFridayActionPerformed(evt);
            }
        });

        cbSterday.setText("Saterday");

        BookPanel.setLayer(LuxuryHallType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(CheckAvailabelPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(btnCheckAvailability, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(btnAddBook, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(btnCancelBook, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(btnUpdateBook, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(btnDeleteBook, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(cmbNoOfDay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(cmbBookType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(cbMonday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(cbSunday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(cbThursday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(cbWednesday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(cbTuesday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(cbFriday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(cbSterday, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout BookPanelLayout = new javax.swing.GroupLayout(BookPanel);
        BookPanel.setLayout(BookPanelLayout);
        BookPanelLayout.setHorizontalGroup(
            BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LuxuryHallType)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookPanelLayout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookPanelLayout.createSequentialGroup()
                                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCheckAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheckAvailabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31))))
                    .addGroup(BookPanelLayout.createSequentialGroup()
                        .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookPanelLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(BookPanelLayout.createSequentialGroup()
                                        .addComponent(btnCancelBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnUpdateBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(BookPanelLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BookPanelLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(cmbBookType, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbNoOfDay, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbMonday, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbThursday, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbFriday, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbSterday, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbSunday, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(191, Short.MAX_VALUE))))
        );
        BookPanelLayout.setVerticalGroup(
            BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckAvailabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBookType, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbNoOfDay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cbSunday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMonday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbThursday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbWednesday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTuesday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbFriday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSterday))
                            .addGroup(BookPanelLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(btnCheckAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpdateBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCancelBook, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38))
                    .addGroup(BookPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(LuxuryHallType, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btnDeleteCustomer.setText("DELETE Customer");
        btnDeleteCustomer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });

        btnAddCustomer.setText("ADD Customer");
        btnAddCustomer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnUpdateCustomer.setText("UPDATE Customer");
        btnUpdateCustomer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });

        txtSearch.setHint("Search");
        txtSearch.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/search.png"))); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jDataTableFD.setBackground(new java.awt.Color(204, 204, 204));
        jDataTableFD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "NIC", "Name", "Telephone Number", "E-Mail", "UserType", "User ID", "date & time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jDataTableFD);

        btnSearch.setText("Search");
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setkBorderRadius(0);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnUserSetings.setText("User Setings");
        btnUserSetings.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnUserSetings.setkBorderRadius(20);
        btnUserSetings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSetingsActionPerformed(evt);
            }
        });

        btnHallSetings.setText("Hall Setings");
        btnHallSetings.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnHallSetings.setkBorderRadius(20);
        btnHallSetings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHallSetingsActionPerformed(evt);
            }
        });

        halltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hall ID", "Hall Cap", "Price Per Day", "AC type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        halltable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                halltableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(halltable);

        javax.swing.GroupLayout gradientBG2Layout = new javax.swing.GroupLayout(gradientBG2);
        gradientBG2.setLayout(gradientBG2Layout);
        gradientBG2Layout.setHorizontalGroup(
            gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBG2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradientBG2Layout.createSequentialGroup()
                        .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gradientBG2Layout.createSequentialGroup()
                                .addGap(749, 749, 749)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientBG2Layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126))
                            .addGroup(gradientBG2Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(BookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gradientBG2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(gradientBG2Layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(btnUserSetings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHallSetings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gradientBG2Layout.setVerticalGroup(
            gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBG2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradientBG2Layout.createSequentialGroup()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUserSetings, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHallSetings, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(gradientBG2Layout.createSequentialGroup()
                        .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gradientBG2Layout.createSequentialGroup()
                                .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gradientBG2Layout.createSequentialGroup()
                                .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 109, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradientBG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gradientBG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNicFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicFDActionPerformed

    private void txtNameFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameFDActionPerformed

    private void txtTeleFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleFDActionPerformed

    private void txtEmailFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFDActionPerformed

    private void btnCheckAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckAvailabilityActionPerformed

    private void btnCheckInFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInFDActionPerformed
        DatePicker checkIn = new DatePicker(this);
        txtCheckInDateFD.setText(checkIn.setPickedDate());
    }//GEN-LAST:event_btnCheckInFDActionPerformed

    private void btnCheckOutFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutFDActionPerformed
        DatePicker checkIn = new DatePicker(this);
        txtCheckOutDateFD.setText(checkIn.setPickedDate());
    }//GEN-LAST:event_btnCheckOutFDActionPerformed

    private void btnSelectLuxuryHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectLuxuryHallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectLuxuryHallActionPerformed

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed


    }//GEN-LAST:event_btnAddBookActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnCancelBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelBookActionPerformed

    private void btnUpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateBookActionPerformed

    private void btnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteBookActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed

        if (validateSubmit()) {
            String nic = txtNicFD.getText();
            UserControler uc = new UserControler();

            if (uc.serachCustomerNic(nic)) {
                String custname = txtNameFD.getText();

                String telephone = txtTeleFD.getText();
                String custEmail = txtEmailFD.getText();

                Customer cust = new Customer();

                cust.setCustomerId(nic);
                cust.setName(custname);
                cust.setTelephoneNumber(telephone);
                cust.setGmail(custEmail);
                cust.setUser(Login.getLoginInstance().getUser());
                cust.setCreateDate("C " + showDateTime());

                uc.addCustomer(cust);

                DataTable();

                txtNameFD.setText("");
                txtNicFD.setText("");
                txtTeleFD.setText("");
                txtEmailFD.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "input fields error");
        }
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed

        if (validateSubmit()) {
            String custname = txtNameFD.getText();
            String nic = txtNicFD.getText();
            String telephone = txtTeleFD.getText();
            String custEmail = txtEmailFD.getText();

            Customer cust = new Customer();

            cust.setCustomerId(nic);
            cust.setName(custname);
            cust.setTelephoneNumber(telephone);
            cust.setGmail(custEmail);
            cust.setUser(Login.getLoginInstance().getUser());
            cust.setCreateDate("U " + Login.getLoginInstance().getUser().getUserType() + " " + showDateTime());

            UserControler uc = new UserControler();
            uc.updateCustomer(cust);

            DataTable();

            txtNameFD.setText("");
            txtNicFD.setText("");
            txtTeleFD.setText("");
            txtEmailFD.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "input fields error");
        }


    }//GEN-LAST:event_btnUpdateCustomerActionPerformed
    String search;
    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed

        if (validateSubmit()) {

            Customer cust = new Customer();
            cust.setCustomerId(search);
            UserControler uc = new UserControler();
            uc.deleteCustomer(cust);

            DataTable();

            txtNameFD.setText("");
            txtNicFD.setText("");
            txtTeleFD.setText("");
            txtEmailFD.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Enter Customer NIC to search and delete");
        }
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed


    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        if (validateSearch()) {
            search = txtSearch.getText();
            UserControler uc = new UserControler();
            Customer cust = uc.customerSearch(search);
            if (cust.getCustomerId() == null) {

                JOptionPane.showMessageDialog(null, "Enter Customer NIC is invalid");
                txtSearch.requestFocus();
            } else {

                txtNameFD.setText(cust.getName());
                txtNicFD.setText(cust.getCustomerId());
                txtTeleFD.setText(cust.getTelephoneNumber());
                txtEmailFD.setText(cust.getGmail());

                txtSearch.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Enter Customer NIC to search ");
        }


    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUserSetingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSetingsActionPerformed

        UserAddingForm uaf = new UserAddingForm();
        uaf.setVisible(true);


    }//GEN-LAST:event_btnUserSetingsActionPerformed

    private void btnHallSetingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHallSetingsActionPerformed
        HallSetingsAdmin hsa = new HallSetingsAdmin();
        hsa.setVisible(true);
    }//GEN-LAST:event_btnHallSetingsActionPerformed

    private void cmbNoOfDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNoOfDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNoOfDayActionPerformed

    private void cmbBookTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBookTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBookTypeActionPerformed

    private void cbFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFridayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFridayActionPerformed

    private void halltableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_halltableMouseClicked
      
        int row=halltable.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)halltable.getModel();
       
        txtHallId.setText(model.getValueAt(row, 0).toString());
         txtCap.setText(model.getValueAt(row, 1).toString());
          txtPrice.setText(model.getValueAt(row, 2).toString());
           txtAc.setText(model.getValueAt(row, 3).toString());
        
        
        
    }//GEN-LAST:event_halltableMouseClicked

    public void DataTable() {

        CustomerControler Cc = new CustomerControler();
        List<Customer> list = Cc.listCustomer();
        DefaultTableModel DFT = (DefaultTableModel) jDataTableFD.getModel();
        DFT.setRowCount(0);
        for (Customer k : list) {

            int no = k.getCustNo();
            String id = k.getCustomerId();
            String name = k.getName();
            String tele = k.getTelephoneNumber();
            String gmail = k.getGmail();
            String userT = k.getUser().getUserType().toString();
            String userID = k.getUser().getUserId();
            String date = k.getCreateDate();

            DFT.addRow(new Object[]{no, id, name, tele, gmail, userT, userID, date});

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AdminMainUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane BookPanel;
    private javax.swing.JLayeredPane CheckAvailabelPanel;
    private javax.swing.JLabel Halltype;
    private javax.swing.JLayeredPane LuxuryHallType;
    private com.abc.view.swing_componont.KButton btnAddBook;
    private com.abc.view.swing_componont.ButtonOutLine btnAddCustomer;
    private com.abc.view.swing_componont.KButton btnCancelBook;
    private com.abc.view.swing_componont.KButton btnCheckAvailability;
    private com.abc.view.swing_componont.ButtonOutLine btnCheckInFD;
    private com.abc.view.swing_componont.ButtonOutLine btnCheckOutFD;
    private com.abc.view.swing_componont.KButton btnDeleteBook;
    private com.abc.view.swing_componont.ButtonOutLine btnDeleteCustomer;
    private com.abc.view.swing_componont.KButton btnHallSetings;
    private com.abc.view.swing_componont.KButton btnSearch;
    private com.abc.view.swing_componont.ButtonOutLine btnSelectLuxuryHall;
    private com.abc.view.swing_componont.KButton btnUpdateBook;
    private com.abc.view.swing_componont.ButtonOutLine btnUpdateCustomer;
    private com.abc.view.swing_componont.KButton btnUserSetings;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox cbFriday;
    private javax.swing.JCheckBox cbMonday;
    private javax.swing.JCheckBox cbSterday;
    private javax.swing.JCheckBox cbSunday;
    private javax.swing.JCheckBox cbThursday;
    private javax.swing.JCheckBox cbTuesday;
    private javax.swing.JCheckBox cbWednesday;
    private javax.swing.JLayeredPane checkInCalender;
    private javax.swing.JLayeredPane checkOutCalender;
    private javax.swing.JLabel checkOutdate;
    private javax.swing.JLabel checkindate;
    private javax.swing.JComboBox<String> cmbBookType;
    private javax.swing.JComboBox<String> cmbNoOfDay;
    private com.abc.view.componont.GradientBG gradientBG2;
    private javax.swing.JTable halltable;
    private javax.swing.JTable jDataTableFD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private textfield.TextFieldSearchOption txt;
    private javax.swing.JTextField txtAc;
    private javax.swing.JTextField txtCap;
    private javax.swing.JLabel txtCheckInDateFD;
    private javax.swing.JLabel txtCheckOutDateFD;
    private javax.swing.JTextField txtEmailFD;
    private javax.swing.JTextField txtHallId;
    private javax.swing.JTextField txtNameFD;
    private javax.swing.JTextField txtNicFD;
    private javax.swing.JTextField txtPrice;
    private com.abc.view.swing_componont.MyTextField txtSearch;
    private javax.swing.JTextField txtTeleFD;
    // End of variables declaration//GEN-END:variables
}
