/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.abc.view.main;

import com.abc.controller.AdminControler;
import com.abc.controller.CustomerControler;
import com.abc.controller.UserControler;
import com.abc.model.Booking;
import com.abc.model.Customer;
import com.abc.model.Hall;
import com.abc.model.Login;
import com.abc.model.User;
import com.abc.view.componont.DatePicker;
import com.abc.view.swing_componont.ButtonOutLine;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CustomerUserView extends javax.swing.JFrame {

    /**
     * Creates new form CustomerUserIView
     */
    private JCheckBox[] checkboxes;
    private int selectedDays;

    public CustomerUserView() {
        initComponents();
        showDate();
        DataTableHall();

        checkboxes = new JCheckBox[7];
        selectedDays = 0;

        checkboxes[0] = cbSunday;
        checkboxes[1] = cbMonday;
        checkboxes[2] = cbTuesday;
        checkboxes[3] = cbWednesday;
        checkboxes[4] = cbThursday;
        checkboxes[5] = cbFriday;
        checkboxes[6] = cbSaterday;
    }

    String checkIndateAM;
    String checkOutdateAM;

    public void showDate() {

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        Date d = new Date();
        txtCheckInDate.setText(sdf.format(d));
        txtCheckOutDate.setText(sdf.format(d));

    }

    private int updateSelectedDays() {
        selectedDays = 0;
        for (int i = 0; i < checkboxes.length; i++) {
            if (checkboxes[i].isSelected()) {

                selectedDays += (int) Math.pow(2, i);
            }
        }
        return selectedDays;
    }

    public boolean validateSubmit() {

        boolean b = false;
        if (txtNicCust.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Customer NIC is requried");
            txtNicCust.requestFocus();
        } else if (txtNameCust.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Customer Name is requried");
            txtNameCust.requestFocus();

        } else if (txtTeleCust.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Customer Telephone Number is requried");
            txtTeleCust.requestFocus();

        } else if (txtEmailCust.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Customer Email is requried");
            txtEmailCust.requestFocus();

        } else if (!(Pattern.matches(EMAIL_PATTERN, txtEmailCust.getText()))) {

            JOptionPane.showMessageDialog(null, "Email is invalid ");

        } else {

            b = true;
        }

        return b;

    }

    private static final String EMAIL_PATTERN
            = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

    public void DataTableHall() {

        UserControler Cc = new UserControler();
        List<Hall> list = Cc.listHallTable();
        DefaultTableModel DFT = (DefaultTableModel) halltableCustomer.getModel();
        DFT.setRowCount(0);
        for (Hall k : list) {

            String htype = k.getHallType();
            String id = k.getHallId();
            String hallCap = k.getHallCap();
            double pricePerDay = k.getPricePerDay();
            String actype = k.getAcType();
            DFT.addRow(new Object[]{htype, id, hallCap, pricePerDay, actype});

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientBG2 = new com.abc.view.componont.GradientBG();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jCalanderPane = new javax.swing.JLayeredPane();
        checkInCalender = new javax.swing.JLayeredPane();
        txtCheckInDate = new javax.swing.JLabel();
        btnCheckIn = new com.abc.view.swing_componont.ButtonOutLine();
        checkindate = new javax.swing.JLabel();
        checkOutCalender = new javax.swing.JLayeredPane();
        txtCheckOutDate = new javax.swing.JLabel();
        btnCheckOut = new com.abc.view.swing_componont.ButtonOutLine();
        checkOutdate = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        txtNicCust = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNameCust = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTeleCust = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmailCust = new javax.swing.JTextField();
        btnSubmitBooking = new com.abc.view.swing_componont.JButtonExtend1();
        HallType = new javax.swing.JLayeredPane();
        lbHalltype = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnSelectLuxuryHall = new com.abc.view.swing_componont.ButtonOutLine();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtHallId = new javax.swing.JTextField();
        txtCap = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtAc = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cmbBookTypeCust = new javax.swing.JComboBox<>();
        cbSunday = new javax.swing.JCheckBox();
        cbMonday = new javax.swing.JCheckBox();
        cbTuesday = new javax.swing.JCheckBox();
        cbWednesday = new javax.swing.JCheckBox();
        cbThursday = new javax.swing.JCheckBox();
        cbFriday = new javax.swing.JCheckBox();
        cbSaterday = new javax.swing.JCheckBox();
        cmbNumberOfDay = new javax.swing.JComboBox<>();
        checkindate1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        halltableCustomer = new javax.swing.JTable();
        cmbHtype = new javax.swing.JComboBox<>();
        btnBack = new com.abc.view.swing_componont.JButtonExtend1();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        checkInCalender.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        txtCheckInDate.setBackground(new java.awt.Color(255, 255, 255));
        txtCheckInDate.setFont(new java.awt.Font("Playbill", 1, 28)); // NOI18N
        txtCheckInDate.setForeground(new java.awt.Color(255, 255, 255));
        txtCheckInDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtCheckInDate.setText("10|02|2023");

        btnCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/cursor (3).png"))); // NOI18N
        btnCheckIn.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        checkInCalender.setLayer(txtCheckInDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        checkInCalender.setLayer(btnCheckIn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout checkInCalenderLayout = new javax.swing.GroupLayout(checkInCalender);
        checkInCalender.setLayout(checkInCalenderLayout);
        checkInCalenderLayout.setHorizontalGroup(
            checkInCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkInCalenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCheckInDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        checkInCalenderLayout.setVerticalGroup(
            checkInCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkInCalenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCheckInDate)
                .addGap(27, 27, 27))
            .addGroup(checkInCalenderLayout.createSequentialGroup()
                .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        checkindate.setBackground(new java.awt.Color(255, 255, 255));
        checkindate.setText("Check In Date");

        checkOutCalender.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        txtCheckOutDate.setBackground(new java.awt.Color(255, 255, 255));
        txtCheckOutDate.setFont(new java.awt.Font("Playbill", 1, 28)); // NOI18N
        txtCheckOutDate.setForeground(new java.awt.Color(255, 255, 255));
        txtCheckOutDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtCheckOutDate.setText("10|02|2023");

        btnCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/cursor (3).png"))); // NOI18N
        btnCheckOut.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        checkOutCalender.setLayer(txtCheckOutDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        checkOutCalender.setLayer(btnCheckOut, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout checkOutCalenderLayout = new javax.swing.GroupLayout(checkOutCalender);
        checkOutCalender.setLayout(checkOutCalenderLayout);
        checkOutCalenderLayout.setHorizontalGroup(
            checkOutCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkOutCalenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCheckOutDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        checkOutCalenderLayout.setVerticalGroup(
            checkOutCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutCalenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCheckOutDate)
                .addGap(27, 27, 27))
            .addGroup(checkOutCalenderLayout.createSequentialGroup()
                .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        checkOutdate.setBackground(new java.awt.Color(255, 255, 255));
        checkOutdate.setText("Check Out Date");

        jCalanderPane.setLayer(checkInCalender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCalanderPane.setLayer(checkindate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCalanderPane.setLayer(checkOutCalender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jCalanderPane.setLayer(checkOutdate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jCalanderPaneLayout = new javax.swing.GroupLayout(jCalanderPane);
        jCalanderPane.setLayout(jCalanderPaneLayout);
        jCalanderPaneLayout.setHorizontalGroup(
            jCalanderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCalanderPaneLayout.createSequentialGroup()
                .addGroup(jCalanderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCalanderPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(checkindate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCalanderPaneLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkInCalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jCalanderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkOutCalender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkOutdate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jCalanderPaneLayout.setVerticalGroup(
            jCalanderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCalanderPaneLayout.createSequentialGroup()
                .addGroup(jCalanderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCalanderPaneLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(checkOutdate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCalanderPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(checkindate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCalanderPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkInCalender, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkOutCalender, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane2.setOpaque(true);

        txtNicCust.setBackground(new java.awt.Color(255, 255, 255));
        txtNicCust.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNicCust.setForeground(new java.awt.Color(0, 73, 227));
        txtNicCust.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 73, 227)));
        txtNicCust.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNicCust.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNicCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicCustActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 73, 227));
        jLabel1.setText("NIC");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 73, 227));
        jLabel2.setText("Enter Your Information");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 73, 227));
        jLabel3.setText("Name");

        txtNameCust.setBackground(new java.awt.Color(255, 255, 255));
        txtNameCust.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameCust.setForeground(new java.awt.Color(0, 73, 227));
        txtNameCust.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 73, 227)));
        txtNameCust.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNameCust.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNameCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameCustActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 73, 227));
        jLabel4.setText("Telephone Number");

        txtTeleCust.setBackground(new java.awt.Color(255, 255, 255));
        txtTeleCust.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTeleCust.setForeground(new java.awt.Color(0, 73, 227));
        txtTeleCust.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 73, 227)));
        txtTeleCust.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTeleCust.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTeleCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleCustActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 73, 227));
        jLabel5.setText("E-Mail");

        txtEmailCust.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailCust.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmailCust.setForeground(new java.awt.Color(0, 73, 227));
        txtEmailCust.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 73, 227)));
        txtEmailCust.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtEmailCust.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEmailCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailCustActionPerformed(evt);
            }
        });

        btnSubmitBooking.setText("Submit Booking");
        btnSubmitBooking.setkBackGroundColor(new java.awt.Color(15, 7, 137));
        btnSubmitBooking.setkBorderRadius(45);
        btnSubmitBooking.setkHoverStartColor(new java.awt.Color(15, 7, 137));
        btnSubmitBooking.setkSelectedColor(new java.awt.Color(15, 7, 137));
        btnSubmitBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitBookingActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(txtNicCust, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtNameCust, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtTeleCust, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtEmailCust, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btnSubmitBooking, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailCust, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeleCust, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameCust, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNicCust, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(btnSubmitBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNicCust, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNameCust, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTeleCust, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailCust, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnSubmitBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        HallType.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        lbHalltype.setBackground(new java.awt.Color(255, 255, 255));
        lbHalltype.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbHalltype.setForeground(new java.awt.Color(255, 255, 255));
        lbHalltype.setText("Halls");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Maximum Capacity");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText(" (Per Person)");

        btnSelectLuxuryHall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/building (4).png"))); // NOI18N
        btnSelectLuxuryHall.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnSelectLuxuryHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectLuxuryHallActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel22.setText("Terms and Conditions apply.");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Price Per Day ");

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Hall ID");

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Air Condithion");

        HallType.setLayer(lbHalltype, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallType.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallType.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallType.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallType.setLayer(btnSelectLuxuryHall, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallType.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallType.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallType.setLayer(txtHallId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallType.setLayer(txtCap, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallType.setLayer(txtPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallType.setLayer(txtAc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallType.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallType.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout HallTypeLayout = new javax.swing.GroupLayout(HallType);
        HallType.setLayout(HallTypeLayout);
        HallTypeLayout.setHorizontalGroup(
            HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HallTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HallTypeLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(HallTypeLayout.createSequentialGroup()
                        .addGroup(HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HallTypeLayout.createSequentialGroup()
                                .addGroup(HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HallTypeLayout.createSequentialGroup()
                                        .addGroup(HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(HallTypeLayout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)))
                                .addGroup(HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHallId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel22)
                            .addComponent(lbHalltype, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HallTypeLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCap, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelectLuxuryHall, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HallTypeLayout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        HallTypeLayout.setVerticalGroup(
            HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HallTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelectLuxuryHall, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HallTypeLayout.createSequentialGroup()
                            .addComponent(lbHalltype, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(HallTypeLayout.createSequentialGroup()
                                    .addGroup(HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(22, 22, 22))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HallTypeLayout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel27)
                                .addComponent(txtHallId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, 0)
                            .addGroup(HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(313, 313, 313)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmbBookTypeCust.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A Given Date", "A Continues Period", "A Specific Day" }));
        cmbBookTypeCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBookTypeCustActionPerformed(evt);
            }
        });

        cbSunday.setText("Sunday");

        cbMonday.setText("Monday");

        cbTuesday.setText("Tuesday");

        cbWednesday.setText("Wednesday");

        cbThursday.setText("Thursday");

        cbFriday.setText("Friday");
        cbFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFridayActionPerformed(evt);
            }
        });

        cbSaterday.setText("Saterday");

        cmbNumberOfDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        checkindate1.setBackground(new java.awt.Color(204, 204, 204));
        checkindate1.setText("Number Of Days");

        halltableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hall Type", "Hall ID", "Hall Cap", "Price Per Day", "AC type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        halltableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                halltableCustomerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(halltableCustomer);

        cmbHtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard Hall", "Benquet Hall", "Luxury Hall" }));
        cmbHtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHtypeActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnBack.setkBorderRadius(65);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jCalanderPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(HallType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cmbBookTypeCust, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbSunday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbMonday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbTuesday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbWednesday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbThursday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbFriday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbSaterday, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cmbNumberOfDay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(checkindate1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cmbHtype, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(HallType)
                        .addGap(67, 67, 67))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmbBookTypeCust, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkindate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbNumberOfDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalanderPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(cbSunday, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbThursday, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(cbMonday, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbFriday, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbSaterday, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmbHtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(HallType, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalanderPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbBookTypeCust, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbNumberOfDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkindate1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSunday)
                    .addComponent(cbTuesday)
                    .addComponent(cbWednesday)
                    .addComponent(cbThursday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMonday)
                    .addComponent(cbFriday)
                    .addComponent(cbSaterday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbHtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout gradientBG2Layout = new javax.swing.GroupLayout(gradientBG2);
        gradientBG2.setLayout(gradientBG2Layout);
        gradientBG2Layout.setHorizontalGroup(
            gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBG2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        gradientBG2Layout.setVerticalGroup(
            gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBG2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNicCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicCustActionPerformed

    private void txtNameCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameCustActionPerformed

    private void txtTeleCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleCustActionPerformed

    private void txtEmailCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailCustActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        MainLoginForm f = new MainLoginForm();
        f.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed

        DatePicker checkIn = new DatePicker(this);
        txtCheckInDate.setText(checkIn.setPickedDate());

    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        DatePicker checkIn = new DatePicker(this);
        txtCheckOutDate.setText(checkIn.setPickedDate());
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnSelectLuxuryHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectLuxuryHallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectLuxuryHallActionPerformed

    private void cmbHtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHtypeActionPerformed

        String value = cmbHtype.getModel().getSelectedItem().toString();

        DataTableHallbyHallType(value);
    }//GEN-LAST:event_cmbHtypeActionPerformed
    public void DataTableHallbyHallType(String hType) {

        UserControler Cc = new UserControler();
        List<Hall> list = Cc.selectHallbyHallType(hType);
        DefaultTableModel DFT = (DefaultTableModel) halltableCustomer.getModel();
        DFT.setRowCount(0);
        for (Hall k : list) {

            String htype = k.getHallType();
            String id = k.getHallId();
            String hallCap = k.getHallCap();
            double pricePerDay = k.getPricePerDay();
            String actype = k.getAcType();
            DFT.addRow(new Object[]{htype, id, hallCap, pricePerDay, actype});

        }
    }
    private void halltableCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_halltableCustomerMouseClicked

        int row = halltableCustomer.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) halltableCustomer.getModel();

        lbHalltype.setText(model.getValueAt(row, 0).toString());
        txtHallId.setText(model.getValueAt(row, 1).toString());
        txtCap.setText(model.getValueAt(row, 2).toString());
        txtPrice.setText(model.getValueAt(row, 3).toString());
        txtAc.setText(model.getValueAt(row, 4).toString());

    }//GEN-LAST:event_halltableCustomerMouseClicked

    private void cmbBookTypeCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBookTypeCustActionPerformed


    }//GEN-LAST:event_cmbBookTypeCustActionPerformed

    private void cbFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFridayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFridayActionPerformed

    private void btnSubmitBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitBookingActionPerformed

        if (checkIndateAM == null && checkOutdateAM == null) {

            JOptionPane.showMessageDialog(null, "Check in date or Check Out date empty");

        } else {
            if (validateSubmit()) {
                String id = txtHallId.getText();
                String custNic = txtNicCust.getText();
                String bookingType = cmbBookTypeCust.getModel().getSelectedItem().toString();

                UserControler uc = new UserControler();
                AdminControler ac = new AdminControler();

                if (id == null || custNic == null) {

                    JOptionPane.showMessageDialog(null, "Hall Id or Customer Nic is empty,please enter");

                } else {

                    if (cmbBookTypeCust.getModel().getSelectedItem().toString().equals("A Specific Day")) {

                        String binaryString = Integer.toBinaryString(updateSelectedDays());

                        int numberOfDays = Integer.parseInt(cmbNumberOfDay.getModel().getSelectedItem().toString());

                        Customer cust = uc.serachCustomerObjbyNic(custNic);
                        Hall hall = ac.searchHallForBooking(id);
                        User user = uc.searchUserObjForBooking(Login.getLoginInstance().getUser().getUserId());
                        Booking book = new Booking();

                        book.setHall(hall);
                        book.setCustomer(cust);
                        book.setUser(user);
                        book.setCheckIn(checkIndateAM);
                        book.setCheckOut(checkOutdateAM);
                        book.setSpecificDay(binaryString);
                        book.setBookingType(bookingType);
                        book.setNumberOfDay(numberOfDays);

                        PaymentForm pf = new PaymentForm();
                        double amount = pf.calcPayment(numberOfDays, hall.getPricePerDay());
                        pf.paymentBill(book, amount);
                        pf.addBookingafterPayment(book);
                        this.setVisible(false);
                        pf.setVisible(true);

                        txtNameCust.setText("");
                        txtNicCust.setText("");
                        txtTeleCust.setText("");
                        txtEmailCust.setText("");

                    } else if (cmbBookTypeCust.getModel().getSelectedItem().toString().equals("A Given Date")) {

                        if (cmbNumberOfDay.getModel().getSelectedItem().toString().equals("1")) {

                            String binaryString = Integer.toBinaryString(updateSelectedDays());

                            int numberOfDays = Integer.parseInt(cmbNumberOfDay.getModel().getSelectedItem().toString());

                            Customer cust = uc.serachCustomerObjbyNic(custNic);

                            Hall hall = ac.searchHallForBooking(id);
                            User user = uc.searchUserObjForBooking(Login.getLoginInstance().getUser().getUserId());
                            Booking book = new Booking();

                            if (checkIndateAM.equals(checkOutdateAM)) {
                                book.setHall(hall);
                                book.setCustomer(cust);
                                book.setUser(user);
                                book.setCheckIn(checkIndateAM);
                                book.setCheckOut(checkOutdateAM);
                                book.setSpecificDay(binaryString);
                                book.setBookingType(bookingType);
                                book.setNumberOfDay(numberOfDays);

                                PaymentForm pf = new PaymentForm();
                                double amount = pf.calcPayment(numberOfDays, hall.getPricePerDay());
                                pf.paymentBill(book, amount);
                                pf.addBookingafterPayment(book);
                                this.setVisible(false);
                                pf.setVisible(true);

                                txtNameCust.setText("");
                                txtNicCust.setText("");
                                txtTeleCust.setText("");
                                txtEmailCust.setText("");
                            } else {
                                JOptionPane.showMessageDialog(null, "Check in date and Check out date must be same day");
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "Number of Days must be 1");
                        }

                    } else {

                        String binaryString = Integer.toBinaryString(updateSelectedDays());
                        int numberOfDays = Integer.parseInt(cmbNumberOfDay.getModel().getSelectedItem().toString());

                        Customer cust = uc.serachCustomerObjbyNic(custNic);
                        Hall hall = ac.searchHallForBooking(id);
                        User user = uc.searchUserObjForBooking(Login.getLoginInstance().getUser().getUserId());
                        Booking book = new Booking();

                        book.setHall(hall);
                        book.setCustomer(cust);
                        book.setUser(user);
                        book.setCheckIn(checkIndateAM);
                        book.setCheckOut(checkOutdateAM);
                        book.setSpecificDay(binaryString);
                        book.setBookingType(bookingType);
                        book.setNumberOfDay(numberOfDays);

                        PaymentForm pf = new PaymentForm();
                        double amount = pf.calcPayment(numberOfDays, hall.getPricePerDay());
                        pf.paymentBill(book, amount);
                        pf.addBookingafterPayment(book);
                        this.setVisible(false);
                        pf.setVisible(true);
                        txtNameCust.setText("");
                        txtNicCust.setText("");
                        txtTeleCust.setText("");
                        txtEmailCust.setText("");
                    }
                }

            }
        }

    }//GEN-LAST:event_btnSubmitBookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerUserView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane HallType;
    private com.abc.view.swing_componont.JButtonExtend1 btnBack;
    private com.abc.view.swing_componont.ButtonOutLine btnCheckIn;
    private com.abc.view.swing_componont.ButtonOutLine btnCheckOut;
    private com.abc.view.swing_componont.ButtonOutLine btnSelectLuxuryHall;
    private com.abc.view.swing_componont.JButtonExtend1 btnSubmitBooking;
    private javax.swing.JCheckBox cbFriday;
    private javax.swing.JCheckBox cbMonday;
    private javax.swing.JCheckBox cbSaterday;
    private javax.swing.JCheckBox cbSunday;
    private javax.swing.JCheckBox cbThursday;
    private javax.swing.JCheckBox cbTuesday;
    private javax.swing.JCheckBox cbWednesday;
    private javax.swing.JLayeredPane checkInCalender;
    private javax.swing.JLayeredPane checkOutCalender;
    private javax.swing.JLabel checkOutdate;
    private javax.swing.JLabel checkindate;
    private javax.swing.JLabel checkindate1;
    private javax.swing.JComboBox<String> cmbBookTypeCust;
    private javax.swing.JComboBox<String> cmbHtype;
    private javax.swing.JComboBox<String> cmbNumberOfDay;
    private com.abc.view.componont.GradientBG gradientBG2;
    private javax.swing.JTable halltableCustomer;
    private javax.swing.JLayeredPane jCalanderPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbHalltype;
    private javax.swing.JTextField txtAc;
    private javax.swing.JTextField txtCap;
    private javax.swing.JLabel txtCheckInDate;
    private javax.swing.JLabel txtCheckOutDate;
    private javax.swing.JTextField txtEmailCust;
    private javax.swing.JTextField txtHallId;
    private javax.swing.JTextField txtNameCust;
    private javax.swing.JTextField txtNicCust;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtTeleCust;
    // End of variables declaration//GEN-END:variables
}
