/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.abc.view.main;

import com.abc.controller.CustomerControler;
import com.abc.controller.UserControler;
import com.abc.model.Customer;
import com.abc.model.Login;
import com.abc.model.User;
import com.abc.view.componont.DatePicker;
import com.abc.view.swing_componont.ButtonOutLine;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FrontDeskUser extends javax.swing.JFrame {

    /**
     * Creates new form CustomerUserIView
     */
    public FrontDeskUser() {
        initComponents();
        showDate();
        DataTable();
        jDataTableFD.setAutoCreateRowSorter(true);

    }

    public String showDateTime() {

        SimpleDateFormat sdf = new SimpleDateFormat("dd|MM|yyyy  HH:mm:ss");
        Date d = new Date();
        String date = sdf.format(d);

        return date;
    }

    public void showDate() {

        SimpleDateFormat sdf = new SimpleDateFormat("dd|MM|yyyy");
        Date d = new Date();
        txtCheckInDateFD.setText(sdf.format(d));
        txtCheckOutDateFD.setText(sdf.format(d));

    }

    public boolean validateSubmit() {

        boolean b = false;
        if (txtNicFD.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Customer NIC is requried");
            txtNicFD.requestFocus();
        } else if (txtNameFD.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Customer Name is requried");
            txtNameFD.requestFocus();

        } else if (txtTeleFD.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Customer Telephone Number is requried");
            txtTeleFD.requestFocus();

        } else if (txtEmailFD.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Customer Email is requried");
            txtEmailFD.requestFocus();

        } else {
            b = true;

        }

        return b;

    }

    public boolean validateSearch() {

        boolean b = false;
        if (txtSearch.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Enter Customer NIC is requried");
            txtSearch.requestFocus();
        } else {

            b = true;

        }

        return b;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientBG2 = new com.abc.view.componont.GradientBG();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        txtNicFD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNameFD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTeleFD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmailFD = new javax.swing.JTextField();
        BookPanel = new javax.swing.JLayeredPane();
        BaanquetHallType = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        cmbBanquetHallID = new javax.swing.JComboBox<>();
        rbBanquetNonAC = new javax.swing.JRadioButton();
        rbBanquetAC = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnSelectBanquetHall = new com.abc.view.swing_componont.ButtonOutLine();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LuxuryHallType = new javax.swing.JLayeredPane();
        jLabel19 = new javax.swing.JLabel();
        cmbLuxuryHallID = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnSelectLuxuryHall = new com.abc.view.swing_componont.ButtonOutLine();
        rbLuxuryNonAC = new javax.swing.JRadioButton();
        rbLuxuryAC = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        StanderdHallType = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        cmbStanderdHallID = new javax.swing.JComboBox<>();
        rbStanderdNonAC = new javax.swing.JRadioButton();
        rbStanderdAC = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnSelectStanderdHall = new com.abc.view.swing_componont.ButtonOutLine();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CheckAvailabelPanel = new javax.swing.JLayeredPane();
        checkInCalender = new javax.swing.JLayeredPane();
        txtCheckInDateFD = new javax.swing.JLabel();
        btnCheckInFD = new com.abc.view.swing_componont.ButtonOutLine();
        checkindate = new javax.swing.JLabel();
        checkOutCalender = new javax.swing.JLayeredPane();
        txtCheckOutDateFD = new javax.swing.JLabel();
        btnCheckOutFD = new com.abc.view.swing_componont.ButtonOutLine();
        checkOutdate = new javax.swing.JLabel();
        kButton2 = new com.abc.view.swing_componont.KButton();
        kButton3 = new com.abc.view.swing_componont.KButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        kButton4 = new com.abc.view.swing_componont.KButton();
        kButton5 = new com.abc.view.swing_componont.KButton();
        kButton6 = new com.abc.view.swing_componont.KButton();
        btnDeleteCustomer = new com.abc.view.swing_componont.ButtonOutLine();
        btnAddCustomer = new com.abc.view.swing_componont.ButtonOutLine();
        btnUpdateCustomer = new com.abc.view.swing_componont.ButtonOutLine();
        txtSearch = new com.abc.view.swing_componont.MyTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDataTableFD = new javax.swing.JTable();
        btnSearch = new com.abc.view.swing_componont.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane2.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 73, 227));
        jLabel1.setText("NIC");

        txtNicFD.setBackground(new java.awt.Color(255, 255, 255));
        txtNicFD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNicFD.setForeground(new java.awt.Color(0, 73, 227));
        txtNicFD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 73, 227)));
        txtNicFD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNicFD.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNicFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicFDActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 73, 227));
        jLabel2.setText("Enter Your Information");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 73, 227));
        jLabel3.setText("Name");

        txtNameFD.setBackground(new java.awt.Color(255, 255, 255));
        txtNameFD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameFD.setForeground(new java.awt.Color(0, 73, 227));
        txtNameFD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 73, 227)));
        txtNameFD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNameFD.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNameFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameFDActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 73, 227));
        jLabel4.setText("Telephone Number");

        txtTeleFD.setBackground(new java.awt.Color(255, 255, 255));
        txtTeleFD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTeleFD.setForeground(new java.awt.Color(0, 73, 227));
        txtTeleFD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 73, 227)));
        txtTeleFD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTeleFD.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTeleFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleFDActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 73, 227));
        jLabel5.setText("E-Mail");

        txtEmailFD.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailFD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmailFD.setForeground(new java.awt.Color(0, 73, 227));
        txtEmailFD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 73, 227)));
        txtEmailFD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtEmailFD.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEmailFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailFDActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtNicFD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtNameFD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtTeleFD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtEmailFD, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailFD, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeleFD, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameFD, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNicFD, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36))))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNicFD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNameFD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTeleFD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailFD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        BaanquetHallType.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Banquet Halls");

        cmbBanquetHallID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBanquetHallID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBanquetHallIDActionPerformed(evt);
            }
        });

        rbBanquetNonAC.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbBanquetNonAC.setText("NON A/C");

        rbBanquetAC.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbBanquetAC.setText("A/C");
        rbBanquetAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBanquetACActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Maximum Capacity- 1000");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Price Per Day -75 000/-");

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel10.setText("Terms and Conditions apply.");

        btnSelectBanquetHall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/building (6).png"))); // NOI18N
        btnSelectBanquetHall.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnSelectBanquetHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectBanquetHallActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" (Per Person)");

        BaanquetHallType.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BaanquetHallType.setLayer(cmbBanquetHallID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BaanquetHallType.setLayer(rbBanquetNonAC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BaanquetHallType.setLayer(rbBanquetAC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BaanquetHallType.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BaanquetHallType.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BaanquetHallType.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BaanquetHallType.setLayer(btnSelectBanquetHall, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BaanquetHallType.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BaanquetHallType.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout BaanquetHallTypeLayout = new javax.swing.GroupLayout(BaanquetHallType);
        BaanquetHallType.setLayout(BaanquetHallTypeLayout);
        BaanquetHallTypeLayout.setHorizontalGroup(
            BaanquetHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaanquetHallTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BaanquetHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BaanquetHallTypeLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(334, 334, 334))
                    .addGroup(BaanquetHallTypeLayout.createSequentialGroup()
                        .addGroup(BaanquetHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(cmbBanquetHallID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BaanquetHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BaanquetHallTypeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbBanquetAC, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbBanquetNonAC)
                                .addGap(177, 177, 177))
                            .addGroup(BaanquetHallTypeLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnSelectBanquetHall, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(BaanquetHallTypeLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        BaanquetHallTypeLayout.setVerticalGroup(
            BaanquetHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaanquetHallTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BaanquetHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BaanquetHallTypeLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBanquetHallID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSelectBanquetHall, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BaanquetHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rbBanquetAC)
                    .addComponent(rbBanquetNonAC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(249, 249, 249)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LuxuryHallType.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Luxury Halls");

        cmbLuxuryHallID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbLuxuryHallID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLuxuryHallIDActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Maximum Capacity- 1500");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText(" (Per Person)");

        btnSelectLuxuryHall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/building (4).png"))); // NOI18N
        btnSelectLuxuryHall.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnSelectLuxuryHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectLuxuryHallActionPerformed(evt);
            }
        });

        rbLuxuryNonAC.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbLuxuryNonAC.setText("NON A/C");

        rbLuxuryAC.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbLuxuryAC.setText("A/C");
        rbLuxuryAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLuxuryACActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel22.setText("Terms and Conditions apply.");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Price Per Day -100 000/-");

        LuxuryHallType.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(cmbLuxuryHallID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(btnSelectLuxuryHall, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(rbLuxuryNonAC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(rbLuxuryAC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LuxuryHallType.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LuxuryHallTypeLayout = new javax.swing.GroupLayout(LuxuryHallType);
        LuxuryHallType.setLayout(LuxuryHallTypeLayout);
        LuxuryHallTypeLayout.setHorizontalGroup(
            LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                        .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addComponent(rbLuxuryAC, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbLuxuryNonAC)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                        .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                                .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(cmbLuxuryHallID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(btnSelectLuxuryHall, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel23))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        LuxuryHallTypeLayout.setVerticalGroup(
            LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSelectLuxuryHall, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbLuxuryHallID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LuxuryHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbLuxuryNonAC)
                            .addComponent(rbLuxuryAC)))
                    .addGroup(LuxuryHallTypeLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)))
                .addGap(316, 316, 316)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StanderdHallType.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Standerd Halls");

        cmbStanderdHallID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStanderdHallID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStanderdHallIDActionPerformed(evt);
            }
        });

        rbStanderdNonAC.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbStanderdNonAC.setForeground(new java.awt.Color(255, 255, 255));
        rbStanderdNonAC.setText("NON A/C");

        rbStanderdAC.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbStanderdAC.setForeground(new java.awt.Color(255, 255, 255));
        rbStanderdAC.setText("A/C");
        rbStanderdAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbStanderdACActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Maximum Capacity- 500");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Price Per Day -50 000/-");

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel15.setText("Terms and Conditions apply.");

        btnSelectStanderdHall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/building (5).png"))); // NOI18N
        btnSelectStanderdHall.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnSelectStanderdHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectStanderdHallActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" (Per Person)");

        StanderdHallType.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StanderdHallType.setLayer(cmbStanderdHallID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StanderdHallType.setLayer(rbStanderdNonAC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StanderdHallType.setLayer(rbStanderdAC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StanderdHallType.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StanderdHallType.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StanderdHallType.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StanderdHallType.setLayer(btnSelectStanderdHall, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StanderdHallType.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StanderdHallType.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout StanderdHallTypeLayout = new javax.swing.GroupLayout(StanderdHallType);
        StanderdHallType.setLayout(StanderdHallTypeLayout);
        StanderdHallTypeLayout.setHorizontalGroup(
            StanderdHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StanderdHallTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StanderdHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StanderdHallTypeLayout.createSequentialGroup()
                        .addGroup(StanderdHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(cmbStanderdHallID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(StanderdHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StanderdHallTypeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbStanderdAC, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbStanderdNonAC)
                                .addGap(177, 177, 177))
                            .addGroup(StanderdHallTypeLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnSelectStanderdHall, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(StanderdHallTypeLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(StanderdHallTypeLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        StanderdHallTypeLayout.setVerticalGroup(
            StanderdHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StanderdHallTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StanderdHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StanderdHallTypeLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStanderdHallID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSelectStanderdHall, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StanderdHallTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rbStanderdAC)
                    .addComponent(rbStanderdNonAC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(249, 249, 249)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        checkInCalender.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        txtCheckInDateFD.setBackground(new java.awt.Color(255, 255, 255));
        txtCheckInDateFD.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        txtCheckInDateFD.setForeground(new java.awt.Color(255, 255, 255));
        txtCheckInDateFD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtCheckInDateFD.setText("10|02|2023");

        btnCheckInFD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/cursor (3).png"))); // NOI18N
        btnCheckInFD.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnCheckInFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInFDActionPerformed(evt);
            }
        });

        checkInCalender.setLayer(txtCheckInDateFD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        checkInCalender.setLayer(btnCheckInFD, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout checkInCalenderLayout = new javax.swing.GroupLayout(checkInCalender);
        checkInCalender.setLayout(checkInCalenderLayout);
        checkInCalenderLayout.setHorizontalGroup(
            checkInCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkInCalenderLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(txtCheckInDateFD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheckInFD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        checkInCalenderLayout.setVerticalGroup(
            checkInCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkInCalenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCheckInDateFD)
                .addGap(27, 27, 27))
            .addGroup(checkInCalenderLayout.createSequentialGroup()
                .addComponent(btnCheckInFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        checkindate.setBackground(new java.awt.Color(204, 204, 204));
        checkindate.setText("Check In Date");

        checkOutCalender.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        txtCheckOutDateFD.setBackground(new java.awt.Color(255, 255, 255));
        txtCheckOutDateFD.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        txtCheckOutDateFD.setForeground(new java.awt.Color(255, 255, 255));
        txtCheckOutDateFD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtCheckOutDateFD.setText("10|02|2023");

        btnCheckOutFD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/cursor (3).png"))); // NOI18N
        btnCheckOutFD.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnCheckOutFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutFDActionPerformed(evt);
            }
        });

        checkOutCalender.setLayer(txtCheckOutDateFD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        checkOutCalender.setLayer(btnCheckOutFD, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout checkOutCalenderLayout = new javax.swing.GroupLayout(checkOutCalender);
        checkOutCalender.setLayout(checkOutCalenderLayout);
        checkOutCalenderLayout.setHorizontalGroup(
            checkOutCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkOutCalenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCheckOutDateFD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheckOutFD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        checkOutCalenderLayout.setVerticalGroup(
            checkOutCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutCalenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCheckOutDateFD)
                .addGap(27, 27, 27))
            .addGroup(checkOutCalenderLayout.createSequentialGroup()
                .addComponent(btnCheckOutFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        checkOutdate.setBackground(new java.awt.Color(204, 204, 204));
        checkOutdate.setText("Check Out Date");

        CheckAvailabelPanel.setLayer(checkInCalender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CheckAvailabelPanel.setLayer(checkindate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CheckAvailabelPanel.setLayer(checkOutCalender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CheckAvailabelPanel.setLayer(checkOutdate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout CheckAvailabelPanelLayout = new javax.swing.GroupLayout(CheckAvailabelPanel);
        CheckAvailabelPanel.setLayout(CheckAvailabelPanelLayout);
        CheckAvailabelPanelLayout.setHorizontalGroup(
            CheckAvailabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckAvailabelPanelLayout.createSequentialGroup()
                .addGroup(CheckAvailabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CheckAvailabelPanelLayout.createSequentialGroup()
                        .addComponent(checkInCalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkOutCalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CheckAvailabelPanelLayout.createSequentialGroup()
                        .addComponent(checkindate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkOutdate)))
                .addContainerGap())
        );
        CheckAvailabelPanelLayout.setVerticalGroup(
            CheckAvailabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckAvailabelPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(CheckAvailabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOutdate)
                    .addComponent(checkindate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CheckAvailabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkInCalender, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkOutCalender, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        kButton2.setText("Check Availability");
        kButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        kButton2.setkBorderRadius(65);
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        kButton3.setText("ADD Book");
        kButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        kButton3.setkBorderRadius(65);
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Select Your Prefered Match");

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("What Day You Looking for");

        kButton4.setText("Cancel Book");
        kButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        kButton4.setkBorderRadius(65);
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });

        kButton5.setText("Update BOOK");
        kButton5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        kButton5.setkBorderRadius(65);
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });

        kButton6.setText("Delete Book");
        kButton6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        kButton6.setkBorderRadius(65);
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });

        BookPanel.setLayer(BaanquetHallType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(LuxuryHallType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(StanderdHallType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(CheckAvailabelPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(kButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(kButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(kButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(kButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        BookPanel.setLayer(kButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout BookPanelLayout = new javax.swing.GroupLayout(BookPanel);
        BookPanel.setLayout(BookPanelLayout);
        BookPanelLayout.setHorizontalGroup(
            BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(StanderdHallType, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BaanquetHallType, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LuxuryHallType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookPanelLayout.createSequentialGroup()
                                .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BookPanelLayout.createSequentialGroup()
                                .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookPanelLayout.createSequentialGroup()
                                        .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)))))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookPanelLayout.createSequentialGroup()
                                .addComponent(CheckAvailabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookPanelLayout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))))))
        );
        BookPanelLayout.setVerticalGroup(
            BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookPanelLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StanderdHallType, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckAvailabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookPanelLayout.createSequentialGroup()
                        .addComponent(BaanquetHallType, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LuxuryHallType, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BookPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
        );

        btnDeleteCustomer.setText("DELETE Customer");
        btnDeleteCustomer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });

        btnAddCustomer.setText("ADD Customer");
        btnAddCustomer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnUpdateCustomer.setText("UPDATE Customer");
        btnUpdateCustomer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });

        txtSearch.setHint("Search");
        txtSearch.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/search.png"))); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jDataTableFD.setBackground(new java.awt.Color(204, 204, 204));
        jDataTableFD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "NIC", "Name", "Telephone Number", "E-Mail", "UserType", "User ID", "date & time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jDataTableFD);

        btnSearch.setText("Search");
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setkBorderRadius(0);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gradientBG2Layout = new javax.swing.GroupLayout(gradientBG2);
        gradientBG2.setLayout(gradientBG2Layout);
        gradientBG2Layout.setHorizontalGroup(
            gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBG2Layout.createSequentialGroup()
                .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradientBG2Layout.createSequentialGroup()
                        .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gradientBG2Layout.createSequentialGroup()
                                .addGap(749, 749, 749)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientBG2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(gradientBG2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        gradientBG2Layout.setVerticalGroup(
            gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBG2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradientBG2Layout.createSequentialGroup()
                        .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gradientBG2Layout.createSequentialGroup()
                        .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gradientBG2, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNicFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicFDActionPerformed

    private void txtNameFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameFDActionPerformed

    private void txtTeleFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleFDActionPerformed

    private void txtEmailFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFDActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2ActionPerformed

    private void cmbBanquetHallIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBanquetHallIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBanquetHallIDActionPerformed

    private void rbBanquetACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBanquetACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBanquetACActionPerformed

    private void btnSelectBanquetHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectBanquetHallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectBanquetHallActionPerformed

    private void btnCheckInFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInFDActionPerformed
        DatePicker checkIn = new DatePicker(this);
        txtCheckInDateFD.setText(checkIn.setPickedDate());
    }//GEN-LAST:event_btnCheckInFDActionPerformed

    private void btnCheckOutFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutFDActionPerformed
        DatePicker checkIn = new DatePicker(this);
        txtCheckOutDateFD.setText(checkIn.setPickedDate());
    }//GEN-LAST:event_btnCheckOutFDActionPerformed

    private void cmbLuxuryHallIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLuxuryHallIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLuxuryHallIDActionPerformed

    private void rbLuxuryACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLuxuryACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLuxuryACActionPerformed

    private void btnSelectLuxuryHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectLuxuryHallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectLuxuryHallActionPerformed

    private void cmbStanderdHallIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStanderdHallIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStanderdHallIDActionPerformed

    private void rbStanderdACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbStanderdACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbStanderdACActionPerformed

    private void btnSelectStanderdHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectStanderdHallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectStanderdHallActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton5ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton6ActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed

        if (validateSubmit()) {
            String nic = txtNicFD.getText();
            UserControler uc = new UserControler();

            if (uc.serachCustomerNic(nic)) {
                String custname = txtNameFD.getText();

                String telephone = txtTeleFD.getText();
                String custEmail = txtEmailFD.getText();

                Customer cust = new Customer();

                cust.setCustomerId(nic);
                cust.setName(custname);
                cust.setTelephoneNumber(telephone);
                cust.setGmail(custEmail);
                cust.setUser(Login.getLoginInstance().getUser());
                cust.setCreateDate("C " + showDateTime());

                uc.addCustomer(cust);

                DataTable();

                txtNameFD.setText("");
                txtNicFD.setText("");
                txtTeleFD.setText("");
                txtEmailFD.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "input fields error");
        }
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed

        if (validateSubmit()) {
            String custname = txtNameFD.getText();
            String nic = txtNicFD.getText();
            String telephone = txtTeleFD.getText();
            String custEmail = txtEmailFD.getText();

            Customer cust = new Customer();

            cust.setCustomerId(nic);
            cust.setName(custname);
            cust.setTelephoneNumber(telephone);
            cust.setGmail(custEmail);
            cust.setUser(Login.getLoginInstance().getUser());
            cust.setCreateDate("U " + Login.getLoginInstance().getUser().getUserType() + " " + showDateTime());

            UserControler uc = new UserControler();
            uc.updateCustomer(cust);

            DataTable();

            txtNameFD.setText("");
            txtNicFD.setText("");
            txtTeleFD.setText("");
            txtEmailFD.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "input fields error");
        }


    }//GEN-LAST:event_btnUpdateCustomerActionPerformed
    String search;
    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed

        if (validateSubmit()) {

            Customer cust = new Customer();
            cust.setCustomerId(search);
            UserControler uc = new UserControler();
            uc.deleteCustomer(cust);

            DataTable();

            txtNameFD.setText("");
            txtNicFD.setText("");
            txtTeleFD.setText("");
            txtEmailFD.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Enter Customer NIC to search and delete");
        }
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed


    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        if (validateSearch()) {
            search = txtSearch.getText();
            UserControler uc = new UserControler();
            Customer cust = uc.customerSearch(search);
            if (cust.getCustomerId() == null) {

                JOptionPane.showMessageDialog(null, "Enter Customer NIC is invalid");
                txtSearch.requestFocus();
            } else {

                txtNameFD.setText(cust.getName());
                txtNicFD.setText(cust.getCustomerId());
                txtTeleFD.setText(cust.getTelephoneNumber());
                txtEmailFD.setText(cust.getGmail());

                txtSearch.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Enter Customer NIC to search ");
        }


    }//GEN-LAST:event_btnSearchActionPerformed

    public void DataTable() {

        CustomerControler Cc = new CustomerControler();
        List<Customer> list = Cc.listCustomer();
        DefaultTableModel DFT = (DefaultTableModel) jDataTableFD.getModel();
        DFT.setRowCount(0);
        for (Customer k : list) {

            int no = k.getCustNo();
            String id = k.getCustomerId();
            String name = k.getName();
            String tele = k.getTelephoneNumber();
            String gmail = k.getGmail();
            String userT = k.getUser().getUserType().toString();
            String userID = k.getUser().getUserId();
            String date = k.getCreateDate();

            DFT.addRow(new Object[]{no, id, name, tele, gmail, userT, userID, date});

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontDeskUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontDeskUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontDeskUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontDeskUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrontDeskUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane BaanquetHallType;
    private javax.swing.JLayeredPane BookPanel;
    private javax.swing.JLayeredPane CheckAvailabelPanel;
    private javax.swing.JLayeredPane LuxuryHallType;
    private javax.swing.JLayeredPane StanderdHallType;
    private com.abc.view.swing_componont.ButtonOutLine btnAddCustomer;
    private com.abc.view.swing_componont.ButtonOutLine btnCheckInFD;
    private com.abc.view.swing_componont.ButtonOutLine btnCheckOutFD;
    private com.abc.view.swing_componont.ButtonOutLine btnDeleteCustomer;
    private com.abc.view.swing_componont.KButton btnSearch;
    private com.abc.view.swing_componont.ButtonOutLine btnSelectBanquetHall;
    private com.abc.view.swing_componont.ButtonOutLine btnSelectLuxuryHall;
    private com.abc.view.swing_componont.ButtonOutLine btnSelectStanderdHall;
    private com.abc.view.swing_componont.ButtonOutLine btnUpdateCustomer;
    private javax.swing.JLayeredPane checkInCalender;
    private javax.swing.JLayeredPane checkOutCalender;
    private javax.swing.JLabel checkOutdate;
    private javax.swing.JLabel checkindate;
    private javax.swing.JComboBox<String> cmbBanquetHallID;
    private javax.swing.JComboBox<String> cmbLuxuryHallID;
    private javax.swing.JComboBox<String> cmbStanderdHallID;
    private com.abc.view.componont.GradientBG gradientBG2;
    private javax.swing.JTable jDataTableFD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.abc.view.swing_componont.KButton kButton2;
    private com.abc.view.swing_componont.KButton kButton3;
    private com.abc.view.swing_componont.KButton kButton4;
    private com.abc.view.swing_componont.KButton kButton5;
    private com.abc.view.swing_componont.KButton kButton6;
    private javax.swing.JRadioButton rbBanquetAC;
    private javax.swing.JRadioButton rbBanquetNonAC;
    private javax.swing.JRadioButton rbLuxuryAC;
    private javax.swing.JRadioButton rbLuxuryNonAC;
    private javax.swing.JRadioButton rbStanderdAC;
    private javax.swing.JRadioButton rbStanderdNonAC;
    private javax.swing.JLabel txtCheckInDateFD;
    private javax.swing.JLabel txtCheckOutDateFD;
    private javax.swing.JTextField txtEmailFD;
    private javax.swing.JTextField txtNameFD;
    private javax.swing.JTextField txtNicFD;
    private com.abc.view.swing_componont.MyTextField txtSearch;
    private javax.swing.JTextField txtTeleFD;
    // End of variables declaration//GEN-END:variables
}
