/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.abc.view.main;

import com.abc.controller.AdminControler;
import com.abc.model.BenquetHalls;
import com.abc.model.Hall;
import com.abc.model.LuxuryHalls;
import com.abc.model.StanderdHalls;
import com.abc.view.componont.DatePicker;
import com.abc.view.swing_componont.ButtonOutLine;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class HallSetingsAdmin extends javax.swing.JFrame {

    /**
     * Creates new form CustomerUserIView
     */
    public HallSetingsAdmin() {
        initComponents();
        showDate();
        DataTable();
        autoDailyMaintenanceUpdate();
        
    }
    
    
    
    public String curentDate(){
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd|MM|yyyy");
    Date d = new Date();
    String date=sdf.format(d);
    
    return date;
    }

    public void showDate() {

        SimpleDateFormat sdf = new SimpleDateFormat("dd|MM|yyyy");
        Date d = new Date();
        txtOutDate.setText(sdf.format(d));
        txtInDate.setText(sdf.format(d));

    }

    public void DataTable() {

        AdminControler Cc = new AdminControler();
        List<Hall> list = Cc.listHalls();
        DefaultTableModel DFT = (DefaultTableModel) HallTable.getModel();
        DFT.setRowCount(0);
        for (Hall k : list) {

            String id = k.getHallId();
            String halltype = k.getHallType();
            String actype = k.getAcType();
            String hallCap = k.getHallCap();
            double pricePerDay = k.getPricePerDay();
            int key = k.getHallNo();
            String State=k.getHallState();
            String inDate=k.getHallInDate();
            String outDate=k.getHallOutDate();

            DFT.addRow(new Object[]{key, id, halltype, actype, hallCap, pricePerDay,State,inDate,outDate});

        }
    }
    
    public void autoDailyMaintenanceUpdate(){
    
    
        AdminControler Cc = new AdminControler();
        Cc.autoDailyMaintenanceUpdateControler(curentDate());
        DataTable();

            

    }

    public boolean validateSearch() {

        boolean b = false;
        if (txtSearch.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Enter search id is requried");
            txtSearch.requestFocus();
        } else {

            b = true;

        }

        return b;

    }

    public boolean validateSubmit() {

        boolean b = false;
        if (txtHallId.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Hall Id is requried");
            txtHallId.requestFocus();
        } else if (txtCapacity.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Hall Capacity is requried");
            txtCapacity.requestFocus();

        } else if (txtPricePerDay.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Price per Day  is requried");
            txtPricePerDay.requestFocus();

        } else if (cmbHallType.getModel().equals(null)) {

            b = false;
            JOptionPane.showMessageDialog(null, "Hall Type is requried");
            cmbHallType.requestFocus();

        } else {
            b = true;

        }

        return b;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        gradientBG2 = new com.abc.view.componont.GradientBG();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        btnMaintenanceAdd = new com.abc.view.swing_componont.JButtonExtend1();
        jLabel14 = new javax.swing.JLabel();
        btnMaintenanceRemove = new com.abc.view.swing_componont.JButtonExtend1();
        checkindate1 = new javax.swing.JLabel();
        checkInCalender1 = new javax.swing.JLayeredPane();
        btnCheckIn1 = new com.abc.view.swing_componont.ButtonOutLine();
        txtOutDate = new javax.swing.JLabel();
        checkindate2 = new javax.swing.JLabel();
        txtMainHallId = new javax.swing.JTextField();
        checkInCalender2 = new javax.swing.JLayeredPane();
        btnCheckIn2 = new com.abc.view.swing_componont.ButtonOutLine();
        txtInDate = new javax.swing.JLabel();
        cmbHallTypeM = new javax.swing.JComboBox<>();
        checkindate3 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        HallDetalis = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        cmbHallType = new javax.swing.JComboBox<>();
        rbNonAC = new javax.swing.JRadioButton();
        rbAC = new javax.swing.JRadioButton();
        btnCheckIn4 = new com.abc.view.swing_componont.ButtonOutLine();
        jLabel11 = new javax.swing.JLabel();
        txtPricePerDay = new com.abc.view.swing_componont.MyTextField();
        checkindate = new javax.swing.JLabel();
        checkOutdate = new javax.swing.JLabel();
        checkOutdate1 = new javax.swing.JLabel();
        checkOutdate2 = new javax.swing.JLabel();
        txtHallId = new com.abc.view.swing_componont.MyTextField();
        txtCapacity = new com.abc.view.swing_componont.MyTextField();
        checkOutdate3 = new javax.swing.JLabel();
        btnHallRemove = new com.abc.view.swing_componont.ButtonOutLine();
        btnHallAdd = new com.abc.view.swing_componont.ButtonOutLine();
        btnHallUpdate = new com.abc.view.swing_componont.ButtonOutLine();
        jScrollPane1 = new javax.swing.JScrollPane();
        HallTable = new javax.swing.JTable();
        txtSearch = new com.abc.view.swing_componont.MyTextField();
        btnSearch = new com.abc.view.swing_componont.JButtonExtend1();
        btnCancel = new com.abc.view.swing_componont.ButtonOutLine();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane2.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 73, 227));
        jLabel2.setText("Maintenance Details");

        btnMaintenanceAdd.setText("ADD");
        btnMaintenanceAdd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnMaintenanceAdd.setkBackGroundColor(new java.awt.Color(15, 7, 137));
        btnMaintenanceAdd.setkBorderRadius(45);
        btnMaintenanceAdd.setkHoverStartColor(new java.awt.Color(15, 7, 137));
        btnMaintenanceAdd.setkSelectedColor(new java.awt.Color(15, 7, 137));
        btnMaintenanceAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaintenanceAddActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(51, 0, 204));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Hall ID");

        btnMaintenanceRemove.setText("REMOVE");
        btnMaintenanceRemove.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnMaintenanceRemove.setkBackGroundColor(new java.awt.Color(15, 7, 137));
        btnMaintenanceRemove.setkBorderRadius(45);
        btnMaintenanceRemove.setkHoverStartColor(new java.awt.Color(15, 7, 137));
        btnMaintenanceRemove.setkSelectedColor(new java.awt.Color(15, 7, 137));
        btnMaintenanceRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaintenanceRemoveActionPerformed(evt);
            }
        });

        checkindate1.setBackground(new java.awt.Color(255, 255, 255));
        checkindate1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        checkindate1.setForeground(new java.awt.Color(0, 0, 153));
        checkindate1.setText("In Date");

        checkInCalender1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));
        checkInCalender1.setForeground(new java.awt.Color(0, 0, 102));

        btnCheckIn1.setBackground(new java.awt.Color(0, 0, 102));
        btnCheckIn1.setForeground(new java.awt.Color(0, 0, 102));
        btnCheckIn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/cursor (3).png"))); // NOI18N
        btnCheckIn1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnCheckIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckIn1ActionPerformed(evt);
            }
        });

        txtOutDate.setBackground(new java.awt.Color(255, 255, 255));
        txtOutDate.setFont(new java.awt.Font("Playbill", 1, 28)); // NOI18N
        txtOutDate.setForeground(new java.awt.Color(0, 0, 102));
        txtOutDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtOutDate.setText("10|02|2023");

        checkInCalender1.setLayer(btnCheckIn1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        checkInCalender1.setLayer(txtOutDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout checkInCalender1Layout = new javax.swing.GroupLayout(checkInCalender1);
        checkInCalender1.setLayout(checkInCalender1Layout);
        checkInCalender1Layout.setHorizontalGroup(
            checkInCalender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkInCalender1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtOutDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheckIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        checkInCalender1Layout.setVerticalGroup(
            checkInCalender1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkInCalender1Layout.createSequentialGroup()
                .addComponent(btnCheckIn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(checkInCalender1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOutDate)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        checkindate2.setBackground(new java.awt.Color(255, 255, 255));
        checkindate2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        checkindate2.setForeground(new java.awt.Color(0, 0, 153));
        checkindate2.setText("Out Date");

        txtMainHallId.setBackground(new java.awt.Color(255, 255, 255));
        txtMainHallId.setForeground(new java.awt.Color(0, 0, 0));
        txtMainHallId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 153)));

        checkInCalender2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));
        checkInCalender2.setForeground(new java.awt.Color(0, 0, 102));

        btnCheckIn2.setBackground(new java.awt.Color(0, 0, 102));
        btnCheckIn2.setForeground(new java.awt.Color(0, 0, 102));
        btnCheckIn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/cursor (3).png"))); // NOI18N
        btnCheckIn2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnCheckIn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckIn2ActionPerformed(evt);
            }
        });

        txtInDate.setBackground(new java.awt.Color(255, 255, 255));
        txtInDate.setFont(new java.awt.Font("Playbill", 1, 28)); // NOI18N
        txtInDate.setForeground(new java.awt.Color(0, 0, 102));
        txtInDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtInDate.setText("10|02|2023");

        checkInCalender2.setLayer(btnCheckIn2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        checkInCalender2.setLayer(txtInDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout checkInCalender2Layout = new javax.swing.GroupLayout(checkInCalender2);
        checkInCalender2.setLayout(checkInCalender2Layout);
        checkInCalender2Layout.setHorizontalGroup(
            checkInCalender2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkInCalender2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtInDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheckIn2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        checkInCalender2Layout.setVerticalGroup(
            checkInCalender2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkInCalender2Layout.createSequentialGroup()
                .addComponent(btnCheckIn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(checkInCalender2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtInDate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmbHallTypeM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard Hall", "Benquet Hall", "Luxury Hall" }));
        cmbHallTypeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHallTypeMActionPerformed(evt);
            }
        });

        checkindate3.setBackground(new java.awt.Color(255, 255, 255));
        checkindate3.setForeground(new java.awt.Color(255, 255, 255));
        checkindate3.setText("Hall Type");

        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btnMaintenanceAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btnMaintenanceRemove, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(checkindate1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(checkInCalender1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(checkindate2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtMainHallId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(checkInCalender2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(cmbHallTypeM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(checkindate3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                        .addComponent(checkindate1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                                        .addComponent(checkInCalender2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)))
                                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMaintenanceRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(checkInCalender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(checkindate2))))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMainHallId, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbHallTypeM, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkindate3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnMaintenanceAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(151, 151, 151))
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(checkindate3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbHallTypeM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMainHallId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkindate1)
                            .addComponent(checkindate2))
                        .addGap(10, 10, 10)
                        .addComponent(checkInCalender2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkInCalender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaintenanceAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaintenanceRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        HallDetalis.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hall Details");

        cmbHallType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard Hall", "Benquet Hall", "Luxury Hall" }));
        cmbHallType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHallTypeActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbNonAC);
        rbNonAC.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbNonAC.setForeground(new java.awt.Color(255, 255, 255));
        rbNonAC.setText("NON A/C");

        buttonGroup1.add(rbAC);
        rbAC.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbAC.setForeground(new java.awt.Color(255, 255, 255));
        rbAC.setText("A/C");
        rbAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbACActionPerformed(evt);
            }
        });

        btnCheckIn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/building (6).png"))); // NOI18N
        btnCheckIn4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnCheckIn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckIn4ActionPerformed(evt);
            }
        });

        txtPricePerDay.setHint("Price Per Day");

        checkindate.setBackground(new java.awt.Color(255, 255, 255));
        checkindate.setForeground(new java.awt.Color(255, 255, 255));
        checkindate.setText("Hall Type");

        checkOutdate.setBackground(new java.awt.Color(255, 255, 255));
        checkOutdate.setForeground(new java.awt.Color(255, 255, 255));
        checkOutdate.setText("Hall ID");

        checkOutdate1.setBackground(new java.awt.Color(255, 255, 255));
        checkOutdate1.setForeground(new java.awt.Color(255, 255, 255));
        checkOutdate1.setText("Price Per DAY");

        checkOutdate2.setBackground(new java.awt.Color(255, 255, 255));
        checkOutdate2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkOutdate2.setText("Air Condition Type");

        txtHallId.setHint("HallID");

        txtCapacity.setHint("Capacity");

        checkOutdate3.setBackground(new java.awt.Color(255, 255, 255));
        checkOutdate3.setForeground(new java.awt.Color(255, 255, 255));
        checkOutdate3.setText("Capacity");

        btnHallRemove.setText("Remove");
        btnHallRemove.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHallRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHallRemoveActionPerformed(evt);
            }
        });

        btnHallAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnHallAdd.setText("ADD");
        btnHallAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHallAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHallAddActionPerformed(evt);
            }
        });

        btnHallUpdate.setText("Update");
        btnHallUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHallUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHallUpdateActionPerformed(evt);
            }
        });

        HallDetalis.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(cmbHallType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(rbNonAC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(rbAC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(btnCheckIn4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(txtPricePerDay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(checkindate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(checkOutdate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(checkOutdate1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(checkOutdate2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(txtHallId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(txtCapacity, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(checkOutdate3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(btnHallRemove, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(btnHallAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        HallDetalis.setLayer(btnHallUpdate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout HallDetalisLayout = new javax.swing.GroupLayout(HallDetalis);
        HallDetalis.setLayout(HallDetalisLayout);
        HallDetalisLayout.setHorizontalGroup(
            HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HallDetalisLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HallDetalisLayout.createSequentialGroup()
                        .addGroup(HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(HallDetalisLayout.createSequentialGroup()
                                .addGroup(HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkOutdate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbHallType, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkindate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkOutdate1)
                                    .addGroup(HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtPricePerDay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                            .addComponent(txtHallId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(checkOutdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HallDetalisLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkOutdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCheckIn4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(17, Short.MAX_VALUE))
                            .addGroup(HallDetalisLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(HallDetalisLayout.createSequentialGroup()
                                        .addComponent(rbAC, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbNonAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(HallDetalisLayout.createSequentialGroup()
                                        .addGroup(HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnHallRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnHallAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnHallUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HallDetalisLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(284, 284, 284))))
        );
        HallDetalisLayout.setVerticalGroup(
            HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HallDetalisLayout.createSequentialGroup()
                .addGroup(HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HallDetalisLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkindate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbHallType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HallDetalisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCheckIn4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkOutdate3)
                    .addComponent(checkOutdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAC)
                    .addComponent(rbNonAC)
                    .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HallDetalisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HallDetalisLayout.createSequentialGroup()
                        .addComponent(checkOutdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHallId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkOutdate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPricePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HallDetalisLayout.createSequentialGroup()
                        .addComponent(btnHallAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHallRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHallUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(HallDetalis, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(HallDetalis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(HallDetalis, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        HallTable.setBackground(new java.awt.Color(204, 204, 204));
        HallTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Hall ID", "Hall Type", "Air Condition", "Capacity", "Price Per Day", "Hall State", "State In Date", "State Out Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(HallTable);

        txtSearch.setHint("Seacrh Hall");
        txtSearch.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/search.png"))); // NOI18N

        btnSearch.setText("Search");
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setkBorderRadius(0);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/cancel (1).png"))); // NOI18N
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gradientBG2Layout = new javax.swing.GroupLayout(gradientBG2);
        gradientBG2.setLayout(gradientBG2Layout);
        gradientBG2Layout.setHorizontalGroup(
            gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBG2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gradientBG2Layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gradientBG2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        gradientBG2Layout.setVerticalGroup(
            gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBG2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(gradientBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gradientBG2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gradientBG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbHallTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHallTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHallTypeActionPerformed

    private void rbACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbACActionPerformed

    private void btnCheckIn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckIn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckIn4ActionPerformed

    String outDate;
    String inDate;
    private void btnCheckIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckIn1ActionPerformed
        DatePicker checkIn = new DatePicker(this);
        txtOutDate.setText(checkIn.setPickedDate());
        outDate=checkIn.setPickedDate();
        
    }//GEN-LAST:event_btnCheckIn1ActionPerformed

    private void btnCheckIn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckIn2ActionPerformed
        DatePicker checkIn = new DatePicker(this);
        txtInDate.setText(checkIn.setPickedDate());
        inDate=checkIn.setPickedDate();
    }//GEN-LAST:event_btnCheckIn2ActionPerformed

    private void btnHallAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHallAddActionPerformed

        if (validateSubmit()) {
            String hallId = txtHallId.getText();
            AdminControler ad = new AdminControler();
            
            if (ad.serachHallId(hallId)) {
            String hallCap = txtCapacity.getText();
            double PricePerDay = Double.parseDouble(txtPricePerDay.getText());
            String airCon;

            if (rbAC.isSelected()) {

                airCon = "AC";
            } else {
                airCon = "NON AC";

            }

            if ((String) cmbHallType.getModel().getSelectedItem() == "Standard Hall") {

                StanderdHalls sd = new StanderdHalls();
                sd.setHallId(hallId);
                sd.setAcType(airCon);
                sd.setPricePerDay(PricePerDay);
                sd.setHallCap(hallCap);
                sd.setHallType((String) cmbHallType.getModel().getSelectedItem());
                sd.setHallState("AVAILABLE");
                sd.setHallInDate("ADD DATE "+curentDate());
                sd.setHallOutDate("continue to BOOK or Maintenance");
                
                ad.addHall(sd);
                DataTable();

            } else if ((String) cmbHallType.getModel().getSelectedItem() == "Benquet Hall") {

                BenquetHalls bq = new BenquetHalls();
                bq.setHallId(hallId);
                bq.setAcType(airCon);
                bq.setPricePerDay(PricePerDay);
                bq.setHallCap(hallCap);
                bq.setHallType((String) cmbHallType.getModel().getSelectedItem());
                bq.setHallState("AVAILABLE");
                bq.setHallInDate("ADD DATE "+curentDate());
                bq.setHallOutDate("continue to BOOK or Maintenance");
                
                ad.addHall(bq);
                DataTable();

            } else {
                LuxuryHalls lx = new LuxuryHalls();
                lx.setHallId(hallId);
                lx.setAcType(airCon);
                lx.setPricePerDay(PricePerDay);
                lx.setHallCap(hallCap);
                lx.setHallType((String) cmbHallType.getModel().getSelectedItem());
                lx.setHallState("AVAILABLE");
                lx.setHallInDate("ADD DATE "+curentDate());
                lx.setHallOutDate("continue to BOOK or Maintenance");
                
                ad.addHall(lx);
                DataTable();

            }
            txtHallId.setText("");
            txtCapacity.setText("");
            txtPricePerDay.setText("");
            cmbHallType.getSelectedItem().equals("");
            rbAC.isSelected();

        } else {
            JOptionPane.showMessageDialog(null, "input fields error");
        }

        }
    }//GEN-LAST:event_btnHallAddActionPerformed

    private void btnHallUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHallUpdateActionPerformed

        if (validateSubmit()) {
            String hallId = txtHallId.getText();
            AdminControler ad = new AdminControler();
            Hall h=ad.searchHall(hallId);
                String hallCap = txtCapacity.getText();
                double PricePerDay = Double.parseDouble(txtPricePerDay.getText());
                String airCon;

                if (rbAC.isSelected()) {

                    airCon = "AC";
                } else {
                    airCon = "NON AC";

                }

                if ((String) cmbHallType.getModel().getSelectedItem() == "Standard Hall") {

                    
                    StanderdHalls sd = new StanderdHalls();
                    sd.setHallId(hallId);
                    sd.setAcType(airCon);
                    sd.setPricePerDay(PricePerDay);
                    sd.setHallCap(hallCap);
                    sd.setHallType((String) cmbHallType.getModel().getSelectedItem());
                    sd.setHallInDate("Hall UPDATE "+curentDate());
                    sd.setHallState(h.getHallState());
                    ad.updateHall(sd);
                    DataTable();

                    txtHallId.setText("");
                    txtCapacity.setText("");
                    txtPricePerDay.setText("");

                } else if ((String) cmbHallType.getModel().getSelectedItem() == "Benquet Hall") {

                    BenquetHalls bq = new BenquetHalls();
                    bq.setHallId(hallId);
                    bq.setAcType(airCon);
                    bq.setPricePerDay(PricePerDay);
                    bq.setHallCap(hallCap);
                    bq.setHallType((String) cmbHallType.getModel().getSelectedItem());
                    bq.setHallInDate("Hall UPDATE "+curentDate());
                    bq.setHallState(h.getHallState());
                    ad.updateHall(bq);
                    DataTable();
                    txtHallId.setText("");
                    txtCapacity.setText("");
                    txtPricePerDay.setText("");

                } else {
                    LuxuryHalls lx = new LuxuryHalls();
                    lx.setHallId(hallId);
                    lx.setAcType(airCon);
                    lx.setPricePerDay(PricePerDay);
                    lx.setHallCap(hallCap);
                    lx.setHallType((String) cmbHallType.getModel().getSelectedItem());
                    lx.setHallInDate("Hall UPDATE "+curentDate());
                    lx.setHallState(h.getHallState());
                    ad.updateHall(lx);
                    DataTable();
                    txtHallId.setText("");
                    txtCapacity.setText("");
                    txtPricePerDay.setText("");

                }
            } else {
                JOptionPane.showMessageDialog(null, "input fields error");
            }

        
    }//GEN-LAST:event_btnHallUpdateActionPerformed
    String search;
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        if (validateSearch()) {

            search = txtSearch.getText();
            AdminControler Ac = new AdminControler();
            Hall h = Ac.searchHall(search);
            if (h.getHallId() == null) {
                JOptionPane.showMessageDialog(null, "Enter User id is invalid");
                txtSearch.requestFocus();
            } else {

                txtHallId.setText(h.getHallId());
                cmbHallType.getModel().setSelectedItem(h.getHallType());
                txtCapacity.setText(h.getHallCap());
                txtPricePerDay.setText(Double.toString(h.getPricePerDay()));
                if (h.getAcType().equals("AC")) {
                    rbAC.setSelected(true);
                } else {
                    rbNonAC.setSelected(true);
                }

                txtSearch.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Enter User id to search ");
        }


    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnHallRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHallRemoveActionPerformed

        if (validateSubmit()) {

            Hall h;
            AdminControler ac = new AdminControler();

            if ((String) cmbHallType.getModel().getSelectedItem() == "Standard Hall") {
                h = new StanderdHalls();
                h.setHallId(search);
                
                ac.hallDelete(h);
                DataTable();
            } else if ((String) cmbHallType.getModel().getSelectedItem() == "Benquet Hall") {
                h = new BenquetHalls();
                h.setHallId(search);
                
                ac.hallDelete(h);
                DataTable();

            } else {

                h = new LuxuryHalls();
                h.setHallId(search);
                
                ac.hallDelete(h);
                DataTable();
            }

            txtHallId.setText("");
            txtCapacity.setText("");
            txtPricePerDay.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Enter User id to search and delete");
        }

    }//GEN-LAST:event_btnHallRemoveActionPerformed

    private void btnMaintenanceAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaintenanceAddActionPerformed
        
        String hallIdM=txtMainHallId.getText();
        
        AdminControler ac = new AdminControler();
        
        Hall sd=null;
        if(inDate != null ){
        
            if(outDate == null ? curentDate() != null : !outDate.equals(curentDate())){
            
               if ((String) cmbHallTypeM.getModel().getSelectedItem() == "Standard Hall") { 
                
                   sd=new StanderdHalls();
                   sd.setHallId(hallIdM);
                   sd.setHallState("MAINTENANCE");
                   sd.setHallInDate("Maintenance ADD "+inDate);
                   sd.setHallOutDate("Maintenance Out "+outDate);
                   ac.addHallMaintenance(sd);
           
               } else if((String) cmbHallType.getModel().getSelectedItem() == "Benquet Hall"){
                   sd=new BenquetHalls();
                   sd.setHallId(hallIdM);
                   sd.setHallState("MAINTENANCE");
                   sd.setHallInDate("Maintenance ADD "+inDate);
                   sd.setHallOutDate("Maintenance Out "+outDate);
                   ac.addHallMaintenance(sd);
               
               
               }else{
               
                   sd=new LuxuryHalls();
                   sd.setHallId(hallIdM);
                   sd.setHallState("MAINTENANCE");
                   sd.setHallInDate("Maintenance ADD "+inDate);
                   sd.setHallOutDate("Maintenance Out "+outDate);
                   ac.addHallMaintenance(sd);
               
               
               }
            }else{
            
            JOptionPane.showMessageDialog(null, "Enter Out date is curent date is not valid");
            
            
            }
        
        }else{
        
        
        JOptionPane.showMessageDialog(null, "please Enter In date above curent date");
        }
     
        DataTable();
        
    }//GEN-LAST:event_btnMaintenanceAddActionPerformed

    private void btnMaintenanceRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaintenanceRemoveActionPerformed
        
        String hallIdM=txtMainHallId.getText();
        
        AdminControler ac = new AdminControler();
        
        Hall sd=null;
        if(inDate != null ){
        
            if(outDate == null ? curentDate() != null : !outDate.equals(curentDate())){
            
               if ((String) cmbHallTypeM.getModel().getSelectedItem() == "Standard Hall") { 
                
                   sd=new StanderdHalls();
                   sd.setHallId(hallIdM);
                   sd.setHallState("AVAILABLE");
                   sd.setHallInDate("Last Maintenance Date  "+curentDate());
                   sd.setHallOutDate("continue to BOOK or Maintenance");
                   ac.removeHallMaintenance(sd);
           
               } else if((String) cmbHallType.getModel().getSelectedItem() == "Benquet Hall"){
                   sd=new BenquetHalls();
                   sd.setHallId(hallIdM);
                   sd.setHallState("AVAILABLE");
                   sd.setHallInDate("Last Maintenance Date  "+curentDate());
                   sd.setHallOutDate("continue to BOOK or Maintenance");
                   ac.removeHallMaintenance(sd);
               
               
               }else{
               
                   sd=new LuxuryHalls();
                   sd.setHallId(hallIdM);
                   sd.setHallState("AVAILABLE");
                   sd.setHallInDate("Last Maintenance Date  "+curentDate());
                   sd.setHallOutDate("continue to BOOK or Maintenance");
                   ac.removeHallMaintenance(sd);
               
               
               }
            }
        
        }
        
    }//GEN-LAST:event_btnMaintenanceRemoveActionPerformed

    private void cmbHallTypeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHallTypeMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHallTypeMActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       
        this.dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HallSetingsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HallSetingsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HallSetingsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HallSetingsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HallSetingsAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane HallDetalis;
    private javax.swing.JTable HallTable;
    private com.abc.view.swing_componont.ButtonOutLine btnCancel;
    private com.abc.view.swing_componont.ButtonOutLine btnCheckIn1;
    private com.abc.view.swing_componont.ButtonOutLine btnCheckIn2;
    private com.abc.view.swing_componont.ButtonOutLine btnCheckIn4;
    private com.abc.view.swing_componont.ButtonOutLine btnHallAdd;
    private com.abc.view.swing_componont.ButtonOutLine btnHallRemove;
    private com.abc.view.swing_componont.ButtonOutLine btnHallUpdate;
    private com.abc.view.swing_componont.JButtonExtend1 btnMaintenanceAdd;
    private com.abc.view.swing_componont.JButtonExtend1 btnMaintenanceRemove;
    private com.abc.view.swing_componont.JButtonExtend1 btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLayeredPane checkInCalender1;
    private javax.swing.JLayeredPane checkInCalender2;
    private javax.swing.JLabel checkOutdate;
    private javax.swing.JLabel checkOutdate1;
    private javax.swing.JLabel checkOutdate2;
    private javax.swing.JLabel checkOutdate3;
    private javax.swing.JLabel checkindate;
    private javax.swing.JLabel checkindate1;
    private javax.swing.JLabel checkindate2;
    private javax.swing.JLabel checkindate3;
    private javax.swing.JComboBox<String> cmbHallType;
    private javax.swing.JComboBox<String> cmbHallTypeM;
    private com.abc.view.componont.GradientBG gradientBG2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbAC;
    private javax.swing.JRadioButton rbNonAC;
    private com.abc.view.swing_componont.MyTextField txtCapacity;
    private com.abc.view.swing_componont.MyTextField txtHallId;
    private javax.swing.JLabel txtInDate;
    private javax.swing.JTextField txtMainHallId;
    private javax.swing.JLabel txtOutDate;
    private com.abc.view.swing_componont.MyTextField txtPricePerDay;
    private com.abc.view.swing_componont.MyTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
