/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.abc.view.main;

import com.abc.controller.AdminControler;

import com.abc.model.Admin;

import com.abc.model.User;
import com.abc.model.UserType;
import static com.abc.model.UserType.ADMIN;
import static com.abc.model.UserType.FRONT_DESK_USER;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class UserAddingForm extends javax.swing.JFrame {

    /**
     * Creates new form UserAddingForm
     */
    public UserAddingForm() {
        
        initComponents();
        loadComboBox();
        DataTable();
        UserDataTable.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientBG1 = new com.abc.view.componont.GradientBG();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbUserType = new javax.swing.JComboBox<>();
        txtUserPassword = new com.abc.view.swing_componont.MyPasswordField();
        txtUserID = new com.abc.view.swing_componont.MyTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserDataTable = new javax.swing.JTable();
        txtSearch = new com.abc.view.swing_componont.MyTextField();
        btnSearch = new com.abc.view.swing_componont.KButton();
        btnUpdate = new com.abc.view.swing_componont.KButton();
        btnDelete = new com.abc.view.swing_componont.KButton();
        btnSubmit = new com.abc.view.swing_componont.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane2.setBackground(new java.awt.Color(153, 153, 153));
        jLayeredPane2.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 73, 227));
        jLabel1.setText("User ID");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 73, 227));
        jLabel2.setText("User Details");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 73, 227));
        jLabel3.setText("User Type");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 73, 227));
        jLabel4.setText("Password");

        cmbUserType.setBackground(new java.awt.Color(255, 255, 255));
        cmbUserType.setForeground(new java.awt.Color(0, 0, 102));
        cmbUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserTypeActionPerformed(evt);
            }
        });

        txtUserPassword.setForeground(new java.awt.Color(0, 0, 51));
        txtUserPassword.setHint("Password");
        txtUserPassword.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/pass.png"))); // NOI18N
        txtUserPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserPasswordActionPerformed(evt);
            }
        });

        txtUserID.setForeground(new java.awt.Color(0, 0, 102));
        txtUserID.setHint("User ID");
        txtUserID.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/id.png"))); // NOI18N

        jLayeredPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(cmbUserType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtUserPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtUserID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserID, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        UserDataTable.setBackground(new java.awt.Color(204, 204, 204));
        UserDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "UserID", "UserType", "Password", "Create Date&Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(UserDataTable);

        txtSearch.setHint("User ID");
        txtSearch.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/com/abc/view/icon/search.png"))); // NOI18N

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gradientBG1Layout = new javax.swing.GroupLayout(gradientBG1);
        gradientBG1.setLayout(gradientBG1Layout);
        gradientBG1Layout.setHorizontalGroup(
            gradientBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBG1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(gradientBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gradientBG1Layout.createSequentialGroup()
                        .addGroup(gradientBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(gradientBG1Layout.createSequentialGroup()
                                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))
                            .addGroup(gradientBG1Layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(gradientBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        gradientBG1Layout.setVerticalGroup(
            gradientBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradientBG1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(gradientBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(gradientBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradientBG1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(gradientBG1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientBG1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    public String showDateTime() {

        SimpleDateFormat sdf = new SimpleDateFormat("dd|MM|yyyy  HH:mm:ss");
        Date d = new Date();
        String date = sdf.format(d);

        return date;
    }

    public void DataTable() {

        AdminControler Cc = new AdminControler();
        List<User> list = Cc.listUser();
        DefaultTableModel DFT = (DefaultTableModel) UserDataTable.getModel();
        DFT.setRowCount(0);
        for (User k : list) {

            String id = k.getUserId();
            String type = k.getUserType().toString();

            String pass = k.getPassword();
            String time = k.getUserCreateDate();
            int key = k.getId();

            DFT.addRow(new Object[]{key, id, type, pass, time});

        }
    }

    public boolean validateSubmit() {

        boolean b = false;
        if (txtUserID.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "User Id is requried");
            txtUserID.requestFocus();
        } else if (txtUserPassword.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Password is requried");
            txtUserPassword.requestFocus();

        } else{
           b = true;

        }

        return b;

    }
    
    public boolean validateSearch() {

        boolean b = false;
        if (txtSearch.getText().equals("")) {

            b = false;
            JOptionPane.showMessageDialog(null, "Enter search id is requried");
            txtSearch.requestFocus();
        } else {

            b = true;

        }

        return b;

    }

    private void loadComboBox() {

        cmbUserType.setModel(new DefaultComboBoxModel<>(UserType.values()));

    }
    private void txtUserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserPasswordActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        if (validateSubmit()) {
            
             String userId = txtUserID.getText();
             AdminControler ac=new AdminControler();
             
            if(ac.serachUserId(userId)){

           
            String password = txtUserPassword.getText();

            if (cmbUserType.getSelectedItem() == ADMIN) {

                Admin admin = new Admin();
                admin.setUserId(userId);
                admin.setUserType((UserType) cmbUserType.getModel().getSelectedItem());
                admin.setPassword(password);
                admin.setUserCreateDate("C " + showDateTime());

               
                ac.addUser(admin);

                DataTable();

                txtUserID.setText("");
                txtUserPassword.setText("");
                cmbUserType.getModel().setSelectedItem("");

            } else {

                User user = new User();
                user.setUserId(userId);
                user.setUserType(UserType.FRONT_DESK_USER);
                user.setPassword(password);
                user.setUserCreateDate("C " + showDateTime());

                AdminControler Aa = new AdminControler();
                Aa.addUser(user);

                DataTable();

                txtUserID.setText("");
                txtUserPassword.setText("");
                cmbUserType.getModel().setSelectedItem("");
            }

        } else {

            
            txtUserID.setText("");
                txtUserPassword.setText("");
                cmbUserType.getModel().setSelectedItem("");

        }
        
        }else{JOptionPane.showMessageDialog(null, "input fields error");}
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void cmbUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserTypeActionPerformed

    }//GEN-LAST:event_cmbUserTypeActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        if (validateSubmit()) {

            String userId = txtUserID.getText();
            String password = txtUserPassword.getText();

            if (cmbUserType.getSelectedItem() == ADMIN) {

                Admin admin = new Admin();
                admin.setUserId(userId);
                admin.setUserType((UserType) cmbUserType.getModel().getSelectedItem());
                admin.setPassword(password);
                admin.setUserCreateDate("U " + showDateTime());

                AdminControler Aa = new AdminControler();
                Aa.updateUser(admin);

                DataTable();

                txtUserID.setText("");
                txtUserPassword.setText("");
                cmbUserType.getModel().setSelectedItem("");

            } else {

                User user = new User();
                user.setUserId(userId);
                user.setUserType(FRONT_DESK_USER);
                user.setPassword(password);
                user.setUserCreateDate("U " + showDateTime());

                AdminControler Aa = new AdminControler();
                Aa.updateUser(user);

                DataTable();

                txtUserID.setText("");
                txtUserPassword.setText("");
                cmbUserType.getModel().setSelectedItem("");

            }
        } else {

            JOptionPane.showMessageDialog(null, "input fields error");


    }//GEN-LAST:event_btnUpdateActionPerformed

    }
    
    String search;
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        if(validateSearch()){
            
        search = txtSearch.getText();   
        AdminControler Ac = new AdminControler();
        User u = Ac.searchUser(search);
        if(u.getUserId()==null){
        JOptionPane.showMessageDialog(null, "Enter User id is invalid");
         txtSearch.requestFocus();
        }else{

        txtUserID.setText(u.getUserId());
        cmbUserType.getModel().setSelectedItem(u.getUserType());
        txtUserPassword.setText(u.getPassword());

        txtSearch.setText("");
        }
        }else{JOptionPane.showMessageDialog(null, "Enter User id to search ");}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        if(validateSubmit()){
        
        User user = new User();
        user.setUserId(search);
        AdminControler ac = new AdminControler();
        ac.userDelete(user);
        DataTable();

        txtUserID.setText("");
        txtUserPassword.setText("");
        cmbUserType.getModel().setSelectedItem("");
        }else{JOptionPane.showMessageDialog(null, "Enter User id to search and delete");}
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAddingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAddingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAddingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAddingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UserAddingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable UserDataTable;
    private com.abc.view.swing_componont.KButton btnDelete;
    private com.abc.view.swing_componont.KButton btnSearch;
    private com.abc.view.swing_componont.KButton btnSubmit;
    private com.abc.view.swing_componont.KButton btnUpdate;
    private javax.swing.JComboBox<UserType> cmbUserType;
    private com.abc.view.componont.GradientBG gradientBG1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.abc.view.swing_componont.MyTextField txtSearch;
    private com.abc.view.swing_componont.MyTextField txtUserID;
    private com.abc.view.swing_componont.MyPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
}
